/** Las personas del árbol. Cada una con su fuente: acta, testimonio o hipótesis. */
const P={
antonio:{n:"Antonio Carlini López",d:"2017",b:"arg",pa:["federico","maia"],
  f:[["Nacimiento","2017, Ciudad de Buenos Aires"],["Ciudadanía","Italiana, declarada por sentencia"]],
  c:[["ACTA-2017-18256686-DGRC, Tomo 3 n. 89/2017"],["Sentenza Tribunale di Trieste, R.G. 7781/2024"]]},
federico:{n:"Federico Carlini",d:"1989",b:"arg",pa:["anibal","patricia"],
  note:"Declarado ciudadano italiano por el Tribunale di Trieste el 30 de abril de 2026, tras fracasar la vía consular entre 2022 y 2024.",
  f:[["Nacimiento","1989, Bella Vista"],["Ciudadanía","Italiana, declarada por sentencia"]],
  sib:["francisco","nicolas","bernardo"],
  c:[["Folio 85, n. 337, Libro de Nacimientos 1989, Oficina de Bella Vista"],
     ["Sentenza Tribunale di Trieste, R.G. 7781/2024","Accerta e dichiara che i ricorrenti sono cittadini italiani"]]},
maia:{n:"Maia López",d:"1987",b:"arg",pa:["josemaria","lidia"],
  note:"Su lugar de nacimiento está en conflicto entre las fuentes familiares: París en una, Argentina en otra.",
  f:[["Nacimiento","1987"]],c:[["Acta de nacimiento de Antonio, 2017"]]},
josemaria:{n:"José María López",d:"?",b:"arg"},
lidia:{n:"Lidia Makaroff",d:"?",b:"arg",
  note:"La transliteración con -off es francesa o alemana, no inglesa: sugiere llegada vía Europa occidental, no la ola migratoria pre-1914."},
anibal:{n:"Aníbal José Carlini",d:"1952",b:"arg",pa:["jfc","haydee"],
  f:[["Nacimiento","28 de octubre de 1952, Mar del Plata"],["Oficio","Comerciante (1978)"],
     ["Estado civil","Viudo de Patricia Novello desde 2003"]],
  c:[["Bella Vista 1978, Matrimonios, acta n. 219"],["Escritura n. 196, 2009"]]},
patricia:{n:"Patricia Novello",d:"1954 – 2003",b:"friuli",pa:["luigi","liliana"],
  f:[["Nacimiento","19 de agosto de 1954, Bella Vista","Su acta de matrimonio dice 19 de septiembre: error de transcripción.",1],
     ["Oficio","Empleada (1978) · archivista (2003)"],["Defunción","24 de mayo de 2003, San Miguel"]],
  sib:["carmen","luisa"],
  c:[["Bella Vista 1954, Nacimientos, acta n. 166"],["Acta de defunción n. 251 I A, 2003"]]},
francisco:{n:"Francisco Carlini",d:"1982",b:"arg",pa:["anibal","patricia"],
  note:"Mellizo de Nicolás. No firma las aceptaciones de venta de 2025 que sí firman sus tres hermanos.",
  f:[["Nacimiento","1982"],["Mellizo","Nacido el mismo día que Nicolás"]]},
nicolas:{n:"Nicolás Carlini",d:"1982",b:"arg",pa:["anibal","patricia"],
  note:"Mellizo de Francisco.",
  f:[["Nacimiento","1982"],["Mellizo","Nacido el mismo día que Francisco"]]},
bernardo:{n:"Bernardo Carlini",d:"1984",b:"arg",pa:["anibal","patricia"],
  f:[["Nacimiento","1984"]]},
clara:{t:1,n:"Clara Canale",d:"—",b:"arg",
  note:"Madre de Felipe y Facundo."},
felipe:{t:1,n:"Felipe Carlini",d:"—",b:"arg",pa:["bernardo","clara"]},
facundo:{t:1,n:"Facundo Carlini",d:"—",b:"arg",pa:["bernardo","clara"]},
carmen:{pa:["giovanniN","idaM"],t:1,n:"Carmen Novello",d:"?",b:"friuli",
  note:"HERMANA DE LUIGI, no de Patricia — corregido por la familia. Es entonces tía abuela de Federico, no tía. Heredera testamentaria de Simón Pedro Bersano, expediente 93450/2019 del Juzgado Nacional Civil 44."},
luisa:{pa:["luigi","liliana"],t:1,n:"Luisa Marina Novello",d:"?",b:"friuli",
  note:"POR CONFIRMAR de qué lado va. Fue declarante en el acta de defunción de Luis Novello en 2021, y heredó junto con Carmen —que resultó ser hermana de Luigi— de Simón Pedro Bersano. Que hereden juntas sugiere que también sea hermana de Luigi. Pero su número de documento corresponde a un nacimiento de alrededor de 1956-58, veintisiete años después de Luigi, y eso encaja mucho mejor con ser hija. Por ahora queda como hija."},

jfc:{n:"José Francisco Calixto Carlini",d:"?",b:"arg",open:1,
  note:"FRONTERA, y la incógnita más resistente. Un investigador de la familia pasó tres meses buscándolo en el Archivio di Stato di Catania, sin resultado. CARLINI no es apellido siciliano: se concentra en Marche, Umbría, Lazio, Emilia y Toscana. Fue buscado en la provincia equivocada.",
  c:[["Bella Vista 1978, Matrimonios, acta n. 219"]]},
haydee:{n:"Haydée Fichera",d:"~1920s",b:"sicilia",pa:["antoninoF","carmelaV"],
  note:"Probablemente bautizada AGATA, por su abuela. El testimonio familiar dice que «Agata terminó siendo Haydée pasando por otros nombres». Si es así, hay que pedir la partida a nombre de Agata.",
  f:[["Nombre de nacimiento","Agata Fichera","Hipótesis apoyada en la costumbre siciliana de nombrar a la nieta como la abuela."]],
  c:[["Testimonio de Juan Lucero, 23-ago-2026"]]},

luigi:{n:"Luigi (Luis) Novello",d:"1929 – 2021",b:"friuli",pa:["giovanniN","idaM"],dc:1,
  note:"El dante causa de la ciudadanía italiana. Nunca se naturalizó argentino, y eso es exactamente lo que mantiene intacta la línea iure sanguinis hasta Federico y Antonio.",
  f:[["Nacimiento","28 de julio de 1929, 20:45 — Latisana (UD)","Aceptada sobre el 31 de julio de la sentencia de Trieste: cinco actos concordantes contra una transcripción judicial.",1],
     ["Bautismo","16 de octubre de 1929"],["Oficio","Meccanico (1953) · jubilado (2021)"],
     ["Servicio militar","Classe 1929, Comune di Latisana"],
     ["Residencia","Las Heras y Lafinur, Bella Vista — 1953"],
     ["Nacionalidad","Italiana, nunca naturalizado argentino"],
     ["Defunción","7 de febrero de 2021, Bella Vista"]],
  c:[["Latisana 1929, Nati, Parte I, n. 130","nato il 28 luglio 1929 alle ore 20:45"],
     ["Latisana 1948, Lista di leva","Novello Luigi, di Giovanni e Morello Ida"],
     ["CNE, certificado 23481/2013"]]},
liliana:{n:"Liliana De Faccio",d:"1929 – 2017",b:"friuli",pa:["gbD","santaC"],
  f:[["Nacimiento","4 de octubre de 1929, 23:00 — Latisana (UD)","La notificación parroquial dice 5 de octubre. Manda el acta civil.",1],
     ["Bautismo","28 de octubre de 1929"],["Oficio","Casalinga (1953) · jubilada (2017)"],
     ["Residencia","San Giorgio di Nogaro (UD) — 1953"],
     ["Nacionalidad","Italiana, nunca naturalizada argentina"],
     ["Defunción","11 de junio de 2017, Bella Vista, a los 87 años"]],
  c:[["Latisana 1929, Nati, Parte I, n. 184","nata il 4 ottobre 1929 alle ore 23:00"],
     ["CNE, certificado 23480/2013"]]},

giovanniN:{img:[["registros/latisana-matrimonios-1892-1901-sin-novello.jpg","Matrimonios 1892-1901: el indice salta de Neri a Odorico. Sin Novello."],["registros/latisana-nacimientos-1892-1901-sin-novello.jpg","Nacimientos 1892-1901: salta de Neri a Olivier. Tampoco."]],url:"https://antenati.cultura.gov.it/ark:/12657/an_ua15621743",n:"Giovanni Novello",d:"~1902",b:"friuli",open:1,
  note:"FRONTERA. Descartado en Latisana revisando página por página los índices decenales, y en toda la provincia de Udine. El apellido se concentra en el Véneto: la familia llegó a Latisana después de 1902.",
  f:[["Nacimiento","~1902","Derivado: declarado de 52 años como testigo en agosto de 1954."],
     ["Oficio","Zapatero"],["Nacionalidad","Italiana"],["Residencia","Bella Vista, 1954"]],
  c:[["Bella Vista 1954, Nacimientos, acta n. 166","Juan Novello, 52 años, italiano, zapatero"]]},
idaM:{img:[["registros/latisana-matrimonios-1892-1901-morello.jpg","Latisana, indice decenal de matrimonios 1892-1901. Los ocho matrimonios Morello de la columna izquierda."]],url:"https://antenati.cultura.gov.it/ark:/12657/an_ua15617238",n:"Ida Morello",d:"?",b:"friuli",open:1,pa:["ferdinandoM","mariaZ"],hyp:1,
  note:"FRONTERA. Candidata única sin confirmar: la Ida Morello nacida el 23 de septiembre de 1895 en Codroipo, hija de Ferdinando Morello y Maria Zanin — es la única Ida Morello indexada en toda la provincia de Udine. En contra: sería siete años mayor que Giovanni. Ojo — en Latisana conviven MORELLO y MURELLO como apellidos distintos: no colapsarlos.",
  f:[["Los Morello sí son de Latisana","Ocho matrimonios Morello en el decenio 1892-1901: Anna (1892, acta 2) · Bernardo (1901, 1) · Carolina (1893, 27) · Francesco (1900, 9) · Giovanni (1896, 21) · Luigi (1897, 26) · Maria (1899, 26) · Teresa (1895, 21).","Entre esos ocho puede estar el matrimonio de los padres de Ida. Hipótesis de trabajo: Giovanni Novello llegó de afuera y se casó con una Morello local."]],
  c:[["Latisana 1948, Lista di leva","di Giovanni e Morello Ida"],
     ["Latisana 1892-1901, Matrimoni, indici decennali, segn. 6520"]]},
gbD:{n:"Giovanni Battista De Faccio",d:"?",b:"friuli",open:1,
  note:"FRONTERA, y la friulana más resistente. Los 514 De Faccio indexados en la provincia de Udine se concentran en Udine ciudad y en Premariacco/Ipplis — no en la Bassa Friulana, que es donde vivía esta familia.",
  f:[["Variantes del nombre","Giobatta · Gio Batta · Juan Bautista"],
     ["Núcleos De Faccio hallados en Udine","Pietro De Faccio × Teresa del Torre · Angelo De Faccio × Domenica Molinari (Ipplis) · Luigi De Faccio × Amabile Morandini · Giuseppe De Faccio × Giuseppina Cattarossi","Ninguno pudo vincularse a Giovanni Battista. Son homónimos de otra zona de la provincia."],
     ["Por qué es difícil","San Giorgio di Nogaro perdió casi todo su archivo comunal anterior a 1918 en la invasión de Caporetto, y no tiene índices decenales de nacimientos en Antenati en ningún decenio.","Sobrevivieron las segundas copias del Tribunale (325 registros) y los libros parroquiales, que no eran del comune. Hay que rutear por el Archivio di Stato y la parroquia, nunca por el comune."],
     ["Trampa técnica","En los índices, «DE FACCIO» puede estar alfabetizado bajo D o bajo F. Hay que revisar las dos."]],
  c:[["San Giorgio di Nogaro 1953, Matrimoni, Parte II Serie A, n. 9","figlia di Giovanni Battista e Cagnolini Santa"],
     ["FamilySearch, Udine 1806-1815 y 1871-1911: 514 registros De Faccio revisados"]]},
santaC:{n:"Santa Cagnolini",d:"?",b:"friuli",open:1,pa:["giuseppeEM"],hyp:1,
  note:"FRONTERA, pero la más cerca de caer. Los Cagnolini son de Latisana y hay tres generaciones reconstruidas. La hipótesis onomástica es fuerte: por la costumbre italiana, una nieta de Santa Pinzani nacida hacia 1900 se habría llamado Santa Cagnolini. El padre más probable es Giuseppe Enrico Marzio, que tendría 20 años en 1900.",
  f:[["Variante del nombre","Santina — y «Cagnolin» en el acta de Patricia"],
     ["Qué falta","Su acta de nacimiento, ~1895-1905, en el Comune di Latisana","Cae después de 1900, donde termina Antenati: no está online, hay que pedirla."]],
  c:[["San Giorgio di Nogaro 1953, Matrimoni, Parte II Serie A, n. 9","figlia di Giovanni Battista e Cagnolini Santa"]]},

antoninoF:{n:"Antonino Fichera",d:"1898",b:"sicilia",pa:["giovanniF","agataC"],
  note:"Lleva el nombre de su abuelo materno, Antonino Castorina — la regla siciliana del segundo varón.",
  f:[["Nacimiento","1898, Acireale"],["Confirmación","14 de febrero de 1908, Diócesis de Acireale"],
     ["Emigración","Embarcó solo en Génova; su mujer lo siguió dos años después. Buque recordado como «Francia».","El buque no pudo confirmarse en la bibliografía de la ruta: sirve para confirmar un candidato, nunca para descartar."],
     ["Oficio","Construcción; dirigente gremial en Mar del Plata"],
     ["Muerte","Accidente de obra: le cayó un ascensor. La familia sostenía que lo habían matado."]],
  sib:["rosarioH","antoninaF","mariaF","giuseppe2"],
  c:[["Diocesi di Acireale, confirmación 14-feb-1908"],["Testimonio de Juan Lucero, 23-ago-2026"]]},
carmelaV:{t:1,n:"Carmela Vaccaro",d:"?",b:"sicilia",open:1,
  note:"Hipótesis. El testimonio familiar menciona el nombre como relevante pero sin ubicar de quién era esposa. Descrita como hija de una familia tradicional de Acireale.",
  c:[["Testimonio de Juan Lucero, 23-ago-2026"]]},
giovanniF:{url:"https://www.familysearch.org/ark:/61903/1:1:XWT7-4LC4",n:"Giovanni Fichera",d:"1869",b:"sicilia",pa:["rosarioF","mariaB"],
  note:"El testimonio oral decía Giarre, jornalero del campo, casado con una Castorina de Acireale. El acta lo confirma palabra por palabra.",
  f:[["Nacimiento","1869, Giarre (Catania)","Derivado de la edad declarada — 26 años — en julio de 1895."],
     ["Oficio","Bracciante — jornalero del campo"],["Matrimonio","25 de julio de 1895, Acireale"]],
  c:[["Acireale 1895, Matrimoni, atto n. 99","Giovanni Fichera, anni 26, nato a Giarre, bracciante"]]},
agataC:{url:"https://www.familysearch.org/ark:/61903/1:1:XWT7-4LC4",n:"Agata Castorina",d:"~1873",b:"sicilia",pa:["antoninoC","veneraP"],
  note:"Su nieta Haydée probablemente fue bautizada Agata en su honor.",
  f:[["Nacimiento","~1873, Acireale","Derivado de la edad declarada — 22 años — en julio de 1895."]],
  c:[["Acireale 1895, Matrimoni, atto n. 99","Agata Castorina, anni 22, di Acireale"]]},
rosarioF:{n:"Rosario Fichera",d:"~1840",b:"sicilia",
  note:"La generación más antigua documentada de toda la familia. Nombrado en el acta de matrimonio de su hijo Giovanni, en 1895.",
  f:[["Residencia","Giarre (Catania)"]],c:[["Acireale 1895, Matrimoni, atto n. 99"]]},
mariaB:{n:"Maria Bonaventura",d:"~1845",b:"sicilia",c:[["Acireale 1895, Matrimoni, atto n. 99"]]},
antoninoC:{n:"Antonino Castorina",d:"1837 – 1905",b:"sicilia",pa:["salvatoreC","angelaM"],
  note:"CASTORINA es un apellido muy característico de Acireale. Su nieto Antonino Fichera lleva su nombre, por la regla siciliana del segundo varón.",
  f:[["Nacimiento","1837, Acireale"],
     ["Matrimonio","3 de junio de 1860, con Venera Privitera"],
     ["Defunción","22 de enero de 1905, Acireale"]],
  c:[["Acireale 1895, Matrimoni, atto n. 99"],
     ["Catania, Stato civile, defunción 22-ene-1905","Antonino Castorina, nato 1837 Acireale, di Salvatore e Angela Motta"],
     ["Diocesi di Acireale, matrimonio 3-giu-1860","figlio di Salvatore Castorina e Angilberga Motto"]]},
veneraP:{n:"Venera Privitera",d:"~1840",b:"sicilia",pa:["francescoP","agataL"],
  f:[["Matrimonio","3 de junio de 1860, Acireale"]],
  c:[["Acireale 1895, Matrimoni, atto n. 99"],
     ["Diocesi di Acireale, matrimonio 3-giu-1860","figlia di Francesco Privitera e Agata Leonardi"]]},
francescoP:{n:"Francesco Privitera",d:"~1815",b:"sicilia",
  note:"Hallado en el registro parroquial del matrimonio de su hija Venera, en 1860. Su nieto Francesco Castorina lleva su nombre, por la regla del segundo varón.",
  c:[["Diocesi di Acireale, matrimonio 3-giu-1860"]]},
agataL:{n:"Agata Leonardi",d:"~1818",b:"sicilia",
  note:"Hallada en el mismo registro de 1860. Su bisnieta Agata Castorina y su tataranieta Haydée (probablemente Agata) llevan su nombre: el nombre viaja cuatro generaciones seguidas por la rama femenina.",
  c:[["Diocesi di Acireale, matrimonio 3-giu-1860"]]},

/* ---- Hermanos de Agata Castorina ---- */
francescoCast:{n:"Francesco Castorina",d:"?",b:"sicilia",pa:["antoninoC","veneraP"],
  note:"Hermano de Agata. Su nombre viene del abuelo materno, Francesco Privitera.",
  c:[["Catania, Stato civile 1866-1929"]]},
salvatoreCast:{n:"Salvatore Castorina",d:"?",b:"sicilia",pa:["antoninoC","veneraP"],
  note:"Hermano de Agata. Su nombre viene del abuelo paterno, Salvatore Castorina. Que los dos hermanos lleven exactamente los nombres que la regla siciliana predice es una confirmación cruzada de toda la reconstrucción.",
  c:[["Catania, Stato civile 1866-1929"]]},
salvatoreC:{n:"Salvatore Castorina",d:"~1810",b:"sicilia",
  note:"Generación nueva, hallada por dos fuentes independientes: el acta de defunción civil de su hijo Antonino (1905) y el registro parroquial de su matrimonio (1860).",
  c:[["Catania, Stato civile, defunción de Antonino Castorina, 22-ene-1905"],
     ["Diocesi di Acireale, matrimonio de Antonino Castorina, 3-giu-1860"]]},
angelaM:{n:"Angela Motta",d:"~1812",b:"sicilia",
  note:"El registro parroquial la anota como «Angilberga Motto» y el civil como «Angela Motta»: la misma persona, dos grafías. Por su generación es la candidata natural a ser la antepasada de ~1812 a la que llegó Juan Lucero por su cuenta — sería una confirmación cruzada, pero está SIN VERIFICAR.",
  c:[["Catania, Stato civile, defunción de Antonino Castorina, 22-ene-1905","di Salvatore e Angela Motta"],
     ["Diocesi di Acireale, matrimonio 3-giu-1860","Angilberga Motto"]]},

/* ---- Hermanos de Giovanni Fichera ---- */
nuntiaF:{n:"Nuntia Fichera",d:"?",b:"sicilia",pa:["rosarioF","mariaB"],
  note:"Hermana de Giovanni. Aparece como novia en los registros parroquiales de la Diócesis de Acireale.",
  c:[["Diocesi di Acireale, Catholic Church Records 1560-1950"]]},
salvatoreF:{n:"Salvatore Fichera",d:"?",b:"sicilia",pa:["rosarioF","mariaB"],
  note:"Hermano de Giovanni. Aparece como novio en los registros parroquiales de la Diócesis de Acireale. Su nombre sugiere que la familia Fichera y la Castorina ya se cruzaban antes de 1895.",
  c:[["Diocesi di Acireale, Catholic Church Records 1560-1950"]]},
rosarioH:{pa:["giovanniF","agataC"],t:1,n:"Rosario Fichera",d:"~1896",b:"sicilia",
  note:"No documentado. La regla siciliana manda que el primer varón lleve el nombre del abuelo paterno — Rosario. El testimonio lo recordaba como «Romario», el hermano mayor.",
  f:[["Dato familiar","Dueño de la casa donde se fundó el Club River Plate de Mar del Plata"]],
  c:[["Testimonio de Juan Lucero, 23-ago-2026"]]},
antoninaF:{pa:["giovanniF","agataC"],n:"Antonina Fichera",d:"1898",b:"sicilia",
  note:"Bautizada el 15 de octubre de 1898, el mismo año que Antonino. O son mellizos, o el índice leyó mal el latín «Antoninus»."},
mariaF:{pa:["giovanniF","agataC"],n:"Maria Fichera",d:"1900",b:"sicilia"},
giuseppe2:{pa:["giovanniF","agataC"],n:"Giuseppe Fichera",d:"1904",b:"sicilia",
  note:"Un hermano anterior con el mismo nombre murió antes de cumplir el año, en 1903. Reutilizar el nombre era práctica habitual."},

/* ---- Hermanos de Liliana: por testimonio familiar, sin documento todavía ---- */
ivonne:{t:1,n:"Ivonne De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermana de Liliana. Sólo por testimonio familiar: no hay documento. «Ivonne» es la forma francesa de Yvonne — llamativa en el Friuli de entreguerras, porque el fascismo desalentaba los nombres extranjeros. Puede indicar un nacimiento posterior a 1945.",
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"]]},
vilma:{t:1,n:"Vilma De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermana de Liliana. Sólo por testimonio familiar. «Vilma» se populariza en Italia en los años 30 y 40.",
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"]]},
franca:{t:1,n:"Franca De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermana de Liliana. Sólo por testimonio familiar. «Franca» es de los nombres más frecuentes en la Italia de los años 30 y 40.",
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"]]},
giorgio:{t:1,n:"Giorgio De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermano de Liliana. Sólo por testimonio familiar. Único nombre tradicional del grupo.",
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"]]},

/* ---- MORELLO: la candidata de Codroipo ---- */
ferdinandoM:{n:"Ferdinando Morello",d:"?",b:"friuli",
  note:"Padre de la única Ida Morello indexada en toda la provincia de Udine. El vínculo con nuestra Ida está SIN CONFIRMAR.",
  c:[["FamilySearch, Udine 1871-1911, nacimiento de Codroipo 1895"]]},
mariaZ:{n:"Maria Zanin",d:"?",b:"friuli",
  c:[["FamilySearch, Udine 1871-1911, nacimiento de Codroipo 1895"]]},

/* ---- CAGNOLINI de Latisana: tres generaciones documentadas ---- */
giuseppeEM:{n:"Giuseppe Enrico Marzio Cagnolini",d:"1880",b:"friuli",pa:["luigiCag","santaPin"],
  note:"Candidato a padre de Santa. Tendría 20 años en 1900, la edad justa. SIN CONFIRMAR: hace falta el acta de nacimiento de Santa.",
  f:[["Nacimiento","29 de agosto de 1880, Latisana"]],
  c:[["Latisana 1880, Nati","Giuseppe Enrico Marzio Cagnolini, di Luigi e Santa Pinzan"]]},
luigiCag:{n:"Luigi Cagnolini",d:"~1840",b:"friuli",
  note:"Padre de al menos cinco hijos en Latisana entre 1867 y 1880.",
  c:[["Latisana, Nati e Matrimoni 1867-1880"]]},
santaPin:{n:"Santa Pinzani",d:"~1845",b:"friuli",
  note:"La clave onomástica de toda esta rama. Por la costumbre italiana, una nieta suya nacida hacia 1900 se habría llamado Santa Cagnolini — que es exactamente el nombre que buscamos.",
  f:[["Variante","Pinzan, en el acta de 1880"]],
  c:[["Latisana, Nati 1867-1880"]]},
andreaCag:{n:"Andrea Cagnolini",d:"~1780",b:"friuli",
  note:"Cabeza de la rama Cagnolini documentada en Latisana. NO se pudo establecer su vínculo con Luigi Cagnolini: son dos núcleos del mismo apellido en el mismo pueblo, sin acta que los una todavía.",
  c:[["Latisana, Morti 1879-1888"]]},
mariannaDon:{n:"Marianna Donati",d:"~1785",b:"friuli",c:[["Latisana, Morti 1879-1888"]]},
carloCag:{n:"Carlo Cagnolini",d:"1808 – 1879",b:"friuli",pa:["andreaCag","mariannaDon"],
  c:[["Latisana, Morti, defunción 3-may-1879"]]},
elisabettaCag:{n:"Elisabetta Cagnolini",d:"1813 – 1881",b:"friuli",pa:["andreaCag","mariannaDon"],
  note:"Casada con Gio Batta Toppani. Una hija suya se llamó Santa Toppani: el nombre circula por las dos ramas de la familia.",
  c:[["Latisana, Morti, defunción 16-jun-1881"]]},
angeloCag:{n:"Angelo Cagnolini",d:"1822 – 1888",b:"friuli",pa:["andreaCag","mariannaDon"],
  c:[["Latisana, Morti, defunción 23-ene-1888"]]},
giuseppeCag:{n:"Giuseppe Cagnolini",d:"1830 – 1898",b:"friuli",pa:["carloCag","caterinaFab"],
  c:[["Latisana, Morti, defunción 9-mar-1898"]]},
caterinaFab:{n:"Caterina Fabbroni",d:"?",b:"friuli",c:[["Latisana, Morti 1879"]]},
carloCag2:{n:"Carlo Cagnolini",d:"1859 – 1892",b:"friuli",pa:["giuseppeCag","teresaMoz"],
  c:[["Latisana, Morti, defunción 19-mar-1892"]]},
teresaMoz:{n:"Teresa Mozzoni",d:"?",b:"friuli",c:[["Latisana, Morti 1898"]]},
};
