/** Las personas del árbol. Cada una con su fuente: acta, testimonio o hipótesis. */
const P={
antonio:{nac:["ar","it"],zn:"Buenos Aires",docs:[["Acta de nacimiento","CABA 2017, Tomo 3 n. 89/2017 — ACTA-2017-18256686-DGRC","tengo"],["Sentencia de ciudadanía","Tribunale di Trieste, R.G. 7781/2024, 30-abr-2026","tengo"]],n:"Antonio Carlini López",d:"2017",b:"arg",pa:["federico","maia"],
  f:[["Nacimiento","2017, Ciudad de Buenos Aires"],["Ciudadanía","Italiana, declarada por sentencia"]],
  c:[["ACTA-2017-18256686-DGRC, Tomo 3 n. 89/2017"],["Sentenza Tribunale di Trieste, R.G. 7781/2024"]]},
federico:{nac:["ar","it"],zn:"Bella Vista",docs:[["Acta de nacimiento","Bella Vista 1989, Libro de Nacimientos, Folio 85 n. 337","tengo"],["Sentencia de ciudadanía","Tribunale di Trieste, R.G. 7781/2024, 30-abr-2026","tengo"]],pr:"Artista visual y músico",n:"Federico Carlini",d:"1989",b:"arg",pa:["anibal","patricia"],
  note:"Declarado ciudadano italiano por el Tribunale di Trieste el 30 de abril de 2026, tras fracasar la vía consular entre 2022 y 2024.",
  f:[["Nacimiento","1989, Bella Vista"],["Ciudadanía","Italiana, declarada por sentencia"]],
  sib:["francisco","nicolas","bernardo"],
  c:[["Folio 85, n. 337, Libro de Nacimientos 1989, Oficina de Bella Vista"],
     ["Sentenza Tribunale di Trieste, R.G. 7781/2024","Accerta e dichiara che i ricorrenti sono cittadini italiani"]]},
maia:{n:"Maia López",d:"1987",b:"arg",pa:["josemaria","lidia"],
  note:"Su lugar de nacimiento está en conflicto entre las fuentes familiares: París en una, Argentina en otra.",
  f:[["Nacimiento","1987"]],c:[["Acta de nacimiento de Antonio, 2017"]]},
josemaria:{n:"José María López",d:"?",b:"arg"},
lidia:{n:"Lidia Makaroff",d:"?",b:"arg",
  note:"La transliteración con -off es francesa o alemana, no inglesa: sugiere llegada vía Europa occidental, no la ola migratoria pre-1914."},
anibal:{nac:["ar"],zn:"Mar del Plata",docs:[["Acta de matrimonio","Bella Vista 1978, Matrimonios, acta n. 219","tengo"],["Acta de nacimiento","Mar del Plata, 28-oct-1952","pedir"]],pr:"Arquitecto y artista plástico",n:"Aníbal José Carlini",d:"1952",b:"arg",pa:["jfc","haydee"],
  f:[["Nacimiento","28 de octubre de 1952, Mar del Plata"],["Oficio","Comerciante (1978)"],
     ["Estado civil","Viudo de Patricia Novello desde 2003"]],
  c:[["Bella Vista 1978, Matrimonios, acta n. 219"],["Escritura n. 196, 2009"]]},
beatrizCarlini:{t:1,n:"Beatriz Carlini",d:"?",b:"arg",pa:["jfc","haydee"],
  note:"Hermana de Aníbal. Se casó con un Lucero y tuvo ONCE hijos, todos con ese apellido — la rama más numerosa de todo el árbol, y con diferencia.\n\nY cierra un círculo: JUAN LUCERO, uno de esos once, es quien en agosto de 2026 dio el testimonio oral que abrió la línea siciliana entera. De ahí salieron Giarre, Agata Castorina, Antonino Fichera y la Vía Galatea de Acireale — todo lo que después las actas confirmaron palabra por palabra. La memoria que sostuvo esta mitad del árbol venía por acá.",
  f:[["Vínculo","Hermana de Aníbal José Carlini"],
     ["Hijos","Once, todos Lucero"],
     ["Falta","El nombre de pila de su marido Lucero"]],
  c:[["Testimonio familiar, 24 de agosto de 2026"]]},
luceroAgustina:{t:1,n:"Agustina Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroLucio:{t:1,n:"Lucio Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroFernando:{t:1,n:"Fernando Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroMariana:{t:1,n:"Mariana Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroCarolina:{t:1,n:"Carolina Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroLuz:{t:1,n:"Luz Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroJulia:{t:1,n:"Julia Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroMercedes:{t:1,n:"Mercedes Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroJuan:{t:1,n:"Juan Lucero",d:"?",b:"arg",pa:["beatrizCarlini"],
  note:"El del testimonio del 23 de agosto de 2026: Giarre, Agata Castorina, Antonino Fichera, la Vía Galatea de Acireale, el barco «Francia». Las actas confirmaron después casi todo lo que contó — y donde no coincidieron, la diferencia sirvió igual para saber dónde mirar.",
  c:[["Testimonio de Juan Lucero, 23-ago-2026"]]},
luceroTomas:{t:1,n:"Tomás Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
luceroLeticia:{t:1,n:"Leticia Lucero",d:"?",b:"arg",pa:["beatrizCarlini"]},
patricia:{nac:["ar"],zn:"Bella Vista",zm:"San Miguel",docs:[["Acta de nacimiento","Bella Vista 1954, Nacimientos, acta n. 166","tengo"],["Acta de matrimonio","Bella Vista 1978, Matrimonios, acta n. 219","tengo"],["Acta de defunción","San Miguel 2003, acta n. 251 I A","tengo"]],pr:"Arquitecta",n:"Patricia Novello",d:"1954 – 2003",b:"friuli",pa:["luigi","liliana"],
  f:[["Nacimiento","19 de agosto de 1954, Bella Vista","Su acta de matrimonio dice 19 de septiembre: error de transcripción.",1],
     ["Oficio","Empleada (1978) · archivista (2003)"],["Defunción","24 de mayo de 2003, San Miguel"]],
  sib:["carmen","luisa"],
  c:[["Bella Vista 1954, Nacimientos, acta n. 166"],["Acta de defunción n. 251 I A, 2003"]]},
francisco:{n:"Francisco Carlini",d:"1982",b:"arg",pa:["anibal","patricia"],
  note:"Mellizo de Nicolás. No firma las aceptaciones de venta de 2025 que sí firman sus tres hermanos.",
  f:[["Nacimiento","1982"],["Mellizo","Nacido el mismo día que Nicolás"]]},
nicolas:{n:"Nicolás Carlini",d:"1982",b:"arg",pa:["anibal","patricia"],
  note:"Mellizo de Francisco.",
  f:[["Nacimiento","1982"],["Mellizo","Nacido el mismo día que Francisco"]]},
bernardo:{n:"Bernardo Carlini",d:"1984",b:"arg",pa:["anibal","patricia"],
  f:[["Nacimiento","1984"]]},
clara:{t:1,n:"Clara Canale",d:"—",b:"arg",
  note:"Madre de Felipe y Facundo."},
felipe:{t:1,n:"Felipe Carlini",d:"—",b:"arg",pa:["bernardo","clara"]},
facundo:{t:1,n:"Facundo Carlini",d:"—",b:"arg",pa:["bernardo","clara"]},
carmen:{pa:["giovanniN","idaM"],t:1,n:"Carmen Novello",d:"?",b:"friuli",
  note:"HERMANA DE LUIGI, no de Patricia — corregido por la familia. Es entonces tía abuela de Federico, no tía. Heredera testamentaria de Simón Pedro Bersano, expediente 93450/2019 del Juzgado Nacional Civil 44."},
luisa:{pa:["luigi","liliana"],t:1,n:"Luisa Marina Novello",d:"?",b:"friuli",
  note:"POR CONFIRMAR de qué lado va. Fue declarante en el acta de defunción de Luis Novello en 2021, y heredó junto con Carmen —que resultó ser hermana de Luigi— de Simón Pedro Bersano. Que hereden juntas sugiere que también sea hermana de Luigi. Pero su número de documento corresponde a un nacimiento de alrededor de 1956-58, veintisiete años después de Luigi, y eso encaja mucho mejor con ser hija. Por ahora queda como hija."},

jfc:{nac:["ar"],zn:"Mar del Plata",zm:"Buenos Aires",n:"José Francisco Calixto Carlini",d:"1916 – 1989",b:"arg",pa:["franciscoCarlini","adelinaDortona"],
  note:"Nació el 6 DE ABRIL DE 1916 en Mar del Plata, acta n. 374. Y esa fecha corrige un problema que estuvo abierto todo el día.\n\nSu acta de bautismo, labrada en la Catedral de Santa Cecilia el 24 de diciembre de 1918 —cuatro años y medio tarde—, decía 6 de abril de 1914. Pero su hermana Carmen nació el 31 de marzo de 1914: entre los dos había SEIS DÍAS, imposible para dos hermanos distintos. La libreta de familia, escrita por el Registro Civil con el acta a la vista, deshace el enredo: el día estaba bien, el año no. Nacieron con dos años exactos de diferencia.\n\nEl perfil familiar cargado en FamilySearch le pone 4 de junio de 1916 — acierta el año y erra el día. Al final la fecha correcta no estaba entera en ninguna de las tres fuentes, sino en el cruce de las tres.\n\nY esa misma tarde apareció la confirmación por un camino aparte. Su acta de defunción, labrada en Buenos Aires el 7 de diciembre de 1989 —setenta y tres años después del nacimiento y con otros funcionarios— dice «nacido en Pcia. Bs. As. el 6 de Abril de 1916». La fecha que había que deducir cruzando tres fuentes estaba escrita, sola y completa, en una cuarta.\n\nSobre el apellido: en 1918 se escribe CARLINI, con i. Pero el diccionario onomástico que la propia FamilySearch adjunta lo define como forma patronímica de CARLINO, y la memoria familiar apunta ahí. La pregunta ya no es cómo se escribía en Mar del Plata sino cómo se escribía en Italia.",
  pr:"Comerciante",
  f:[["Nacimiento","6 de abril de 1916, Mar del Plata","Libreta de Familia, acta n. 374. Manda sobre el 6-abr-1914 del bautismo tardío de 1918 y sobre el 4-jun-1916 del perfil familiar.",1],
     ["Bautismo","24 de diciembre de 1918, Catedral de Santa Cecilia, Mar del Plata"],
     ["Nombre como fue escrito","José Francisco Calixto Carlini Dortona"],
     ["Casado con","Haydée Fichera"],
     ["Domicilio","Corrientes 4167, Buenos Aires","Al morir."],
     ["Documento","C.I. 10.422.805"],
     ["Defunción","6 de diciembre de 1989, 17:50 — Cabello 3881, Buenos Aires","Paro cardiorrespiratorio no traumático. Certificó el Dr. Alfredo Horton. Acta n. 1799, tomo 3C, inscripta el 7 de diciembre de 1989.",1]],
  img:[["registros/libreta-familia-defuncion-hijos.jpg","Libreta de Familia: los nacimientos de Carmen (1914) y José Francisco Calixto (1916), anotados por el Registro Civil."]],
  docs:[["Acta de nacimiento","Mar del Plata, 6-abr-1916, acta n. 374","tengo"],
        ["Acta de defunción","Registro Civil de la Capital, Departamento Central, tomo 3C n. 1799, año 1989","tengo"],
        ["Acta de bautismo","Mar del Plata, Catedral Santa Cecilia, 24-dic-1918","online"],
        ["Acta de matrimonio","Mar del Plata, con Haydée Fichera, ~1945-1952","pedir"]],
  c:[["Registro Civil de la Capital, defunción, 7-dic-1989, tomo 3C n. 1799","«JOSÉ FRANCISCO CALIXTO CARLINI… hijo de Francisco Carlini y de Adelina Ortona, nacido en Pcia. Bs. As. el 6 de Abril de 1916»"],
     ["Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913","Don José Francisco Calixto, nació el 6 de Abril de 1916 en Mar del Plata, acta n. 374"],
     ["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Mar del Plata, Catedral Santa Cecilia","bautizado 24 de diciembre de 1918, hijo de Francisco Carlini y Adelina Dortona"],
     ["Bella Vista 1978, Matrimonios, acta n. 219"]]},
franciscoCarlini:{nac:["it"],zn:"Italia",zm:"Tandil",n:"Francisco Carlini",d:"1884 – 1945",b:"arg",open:1,pa:["joseCarlini","carmenGeraci"],
  note:"EL INMIGRANTE. Durante meses fue una frontera con dos datos sueltos de memoria familiar; el 24 de agosto de 2026 su nieta Beatriz apareció con la LIBRETA DE FAMILIA y todo quedó escrito.\n\nNació en Italia un día de julio de 188· —el día quedó en blanco y el último dígito del año está tapado por una firma—, era EMPLEADO, y en mayo de 1913 vivía en la calle Luca 1667 de Buenos Aires, en la misma casa que su novia. Se casaron el 21 de mayo en el Registro Civil de la Capital, acta n. 238.\n\nY el otro dato: MURIÓ EL 17 DE OCTUBRE DE 1945 EN TANDIL, acta n. 222 tomo 1º. La memoria familiar decía Tandil sin poder probarlo. Ahí está el sello del Registro Civil de Tandil y la firma de Nicolás P. Petilo.",
  pr:"Empleado",
  f:[["Nacimiento","Italia, julio de 1884","El año lo aporta Beatriz Carlini, su nieta, el 24 de agosto de 2026. En la libreta el día quedó en blanco y el último dígito del año está tapado por una firma, así que el documento solo permite acotar entre 1884 y 1889: el testimonio cae adentro de esa horquilla. No la contradice — la precisa.",1],
     ["Oficio","Empleado"],
     ["Domicilio en 1913","Calle Luca 1667, Buenos Aires","La misma dirección que Adelina: vivían juntos antes de casarse."],
     ["Matrimonio","21 de mayo de 1913, Registro Civil de la Capital, Buenos Aires, acta n. 238"],
     ["Defunción","17 de octubre de 1945, Tandil","Acta n. 222, tomo 1º. Confirma lo que la familia recordaba sin papel."]],
  img:[["registros/libreta-familia-1913-matrimonio.jpg","Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913. Acta n. 238 del 21 de mayo. Nombra a los cuatro padres."],["registros/libreta-familia-defuncion-hijos.jpg","La misma libreta: la muerte de Francisco en Tandil el 17 de octubre de 1945, y los dos primeros hijos."]],
  docs:[["Acta de matrimonio","Registro Civil de la Capital, Buenos Aires, 21-may-1913, acta n. 238","tengo"],
        ["Acta de defunción","Registro Civil de Tandil, 17-oct-1945, acta n. 222 tomo 1º","tengo"],
        ["Acta de nacimiento","Italia, julio de 1884 — comune sin identificar","pedir"]],
  c:[["Testimonio de Beatriz Carlini, 24-ago-2026","Nació en 1884. Es su nieta, y es quien aportó la libreta de familia."],
     ["Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913, acta n. 238","Don Francisco Carlini, hijo de Don José id. y de Doña Carmen Geraci, nacido en Italia el de Julio de 188·, profesión empleado, domiciliado en la calle Luca 1667"],
     ["Ídem, Muerte de los esposos","Muerto el 17 de Octubre 1945 en Tandil, acta n. 222 tomo 1º"]]},
joseCarlini:{f:[["El apellido no cierra","CARLINI es del centro de Italia; CARLINO es 34% siciliano","Carlini: 10.664 en Italia, Lazio 23%, Emilia-Romaña 19%, Liguria 12% — Sicilia no figura entre sus regiones. Carlino: 7.566, y el 34% en SICILIA, con 563 familias en la isla. Un Carlini de Lazio casado con una Geraci siciliana es raro; un Carlino siciliano casado con una Geraci es lo normal. Sumado a que el diccionario onomástico de FamilySearch define Carlini como forma patronímica de Carlino, y a la memoria familiar, la hipótesis es que la familia era CARLINO y el apellido se escribió Carlini en la Argentina. En la Argentina hay ~1.100 portadores de cada forma: se confunden sin esfuerzo."],
     ["Dónde buscarlo","Sicilia, como CARLINO","Hasta ahora se buscaba Carlini en Sicilia, que es buscar un apellido donde casi no existe."]],n:"José Carlini",d:"?",b:"arg",open:1,
  note:"Padre de Francisco, aparecido el 24 de agosto de 2026 en la libreta de familia. La libreta lo anota como «Don José id.» — el «id.» es ídem, o sea el mismo apellido del contrayente: Carlini. Es la primera vez que esta rama llega a una generación anterior al inmigrante.\n\nDe él no se sabe nada más todavía: ni dónde nació, ni si cruzó el Atlántico o se quedó en Italia. Lo diría el acta de nacimiento de Francisco, que es el documento que falta.",
  c:[["Libreta de Familia, Buenos Aires 1913, acta n. 238","Hijo de Don José id."]]},
carmenGeraci:{n:"Carmen Geraci",d:"?",b:"sicilia",open:1,
  note:"Madre de Francisco. Y su apellido es un dato en sí mismo: GERACI es siciliano y se concentra en las provincias de Messina y Palermo. Hasta ahora lo siciliano de esta rama entraba sólo por Adelina; el apellido de la suegra dice que Francisco también podría ser de la isla.\n\nY encaja con la otra punta que apareció el mismo día: la tía Elda se carteaba con parientes en Messina. Dos indicios independientes, la misma provincia.",
  f:[["Apellido","Geraci — siciliano, del pueblo de Geraci Siculo (Palermo)","Es un apellido de procedencia. Sale de GERACI SICULO, en la provincia de PALERMO; del griego hierax, halcón, latinizado Geracium en la Sicilia bizantina. Hay Geraci también en Calabria. Apunta a Palermo, no a la costa jónica donde están los Fichera: son dos historias sicilianas distintas que se cruzaron recién en Buenos Aires."],],
  c:[["Libreta de Familia, Buenos Aires 1913, acta n. 238","y de Doña Carmen Geraci"]]},
adelinaDortona:{nac:["it"],zn:"Italia",n:"Adelina D'Ortona",d:"1899",b:"sicilia",open:1,pa:["joseDortona","carmenSaffialardo"],
  note:"La abuela paterna de Aníbal, y desde el 24 de agosto de 2026 una persona con biografía. La libreta de familia dice: nacida en Italia el 2 DE JUNIO DE 1899, de profesión MODISTA, domiciliada en la calle Luca 1667 de Buenos Aires — la misma casa que Francisco.\n\nSe casaron el 21 de mayo de 1913. Si la fecha de nacimiento es exacta, tenía TRECE AÑOS. Es una edad que hoy resulta impensable y que entonces el Código Civil argentino todavía permitía; también puede ser que el escribiente errara el año. Se anota como está escrito, sin corregir: el dato es del documento, no mío.\n\nSobrevivió a Francisco, que murió en 1945: la mitad de «MUJER» en la página de defunciones quedó en blanco.",
  pr:"Modista",
  f:[["Nacimiento","2 de junio de 1899, Italia","Tal como lo escribe la libreta. Daría trece años al casarse, lo que abre la duda de si el año es correcto."],
     ["Oficio","Modista"],
     ["Domicilio en 1913","Calle Luca 1667, Buenos Aires"],
     ["Matrimonio","21 de mayo de 1913, Registro Civil de la Capital, acta n. 238"],
     ["Origen","En disputa: el apellido dice ABRUZZO, la memoria dice Messina","D'Ortona lo llevan 589 personas en Italia y el 88% vive en ABRUZZO — la región de Chieti, donde está el pueblo de Ortona del que sale el apellido. Contra eso, «Sicilia» viene de un árbol colaborativo sin fuente, y Messina de que su hija Elda se carteaba con parientes de ahí en los años cincuenta: eso dice dónde vivía alguien medio siglo después, no dónde nació ella en 1899. El acta de matrimonio de 1913, íntegra, lo resuelve."],
     ["Variantes","Dortona en el bautismo de 1918 · D'Ortona en la libreta"]],
  img:[["registros/libreta-familia-1913-matrimonio.jpg","Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913. Acta n. 238 del 21 de mayo. Nombra a los cuatro padres."]],
  docs:[["Acta de matrimonio","Registro Civil de la Capital, Buenos Aires, 21-may-1913, acta n. 238","tengo"],
        ["Acta de nacimiento","Italia, 2-jun-1899 — comune sin identificar. Empezar por Messina","pedir"],
        ["Acta de defunción","Posterior a 1945, lugar sin determinar","pedir"]],
  c:[["Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913, acta n. 238","Doña Adelina D'Ortona, hija de Don José id. y de Doña Carmen Saffialardo, nacida en Italia el 2 de Junio de 1899, profesión modista, domiciliada en la calle Luca 1667"]]},
joseDortona:{f:[["Apellido","D'Ortona — abruzzese, de la comarca de Chieti","589 portadores en Italia, 88% en Abruzzo. El apellido es literalmente un domicilio: «el de Ortona», el pueblo de la provincia de Chieti. Hay además presencia documentada en la Argentina."]],n:"José D'Ortona",d:"?",b:"sicilia",open:1,
  note:"Padre de Adelina, nombrado en la libreta como «Don José id.» — ídem, mismo apellido que la contrayente. Nada más se sabe de él todavía.\n\nUna curiosidad que conviene mirar con cuidado: los dos padres se llaman José y las dos madres Carmen. Puede ser casualidad —eran los nombres más comunes de la época— o puede ser que el escribiente se dejara llevar por la simetría. Vale tenerlo presente cuando aparezca otro documento que los nombre.",
  c:[["Libreta de Familia, Buenos Aires 1913, acta n. 238","Hija de Don José id."]]},
carmenSaffialardo:{n:"Carmen Saffialardo",d:"?",b:"sicilia",open:1,hyp:1,
  note:"Madre de Adelina. El apellido está escrito a mano por un oficial argentino tomando de oído un apellido italiano, y la lectura no es segura: podría ser Saffialardo, Saffalardo, Scaffalardo o Sciafalardo. Ninguna de las cuatro es un apellido italiano frecuente, lo que sugiere que la grafía se deformó al cruzar el idioma.\n\nSe deja como hipótesis por eso: la persona existió y está nombrada en el acta, pero el apellido con el que buscarla todavía no es confiable.",
  f:[["Apellido","No existe como apellido italiano","Buscado como Saffialardo, Saffalardo, Scaffalardo y Sciafalardo: ninguno figura como apellido italiano. Confirma que es una transcripción de oído hecha por un oficial argentino en 1913. Candidatos reales que terminan igual: PAPPALARDO —muy frecuente en Catania y Messina—, Milardo, Gagliardo, Filardo."],["Lectura del apellido","Incierta","Saffialardo · Saffalardo · Scaffalardo · Sciafalardo. Escrito de oído por un oficial argentino."]],
  c:[["Libreta de Familia, Buenos Aires 1913, acta n. 238","y de Doña Carmen Saffialardo"]]},
eldaCarlini:{nac:["ar"],zn:"Mar del Plata",n:"Elda Angélica Carlini d'Ortona",d:"1925",b:"arg",pa:["franciscoCarlini","adelinaDortona"],
  note:"La menor, y la que mantuvo viva la punta italiana: SE CARTEABA CON PARIENTES D'ORTONA, y el recuerdo familiar los ubica en MESSINA. Es la mejor pista que hay sobre de dónde vino su madre.\n\nEl 24 de agosto de 2026 pasó de recuerdo a documento: la libreta de familia la registra nacida el 6 DE SEPTIEMBRE DE 1925 en Mar del Plata, acta n. 1026, con su nombre entero — Elda Angélica.\n\nSe casó con un Durán. De sus hijos, los mayores fallecieron; con los menores casi no hubo contacto, y la mudanza de la familia a Buenos Aires terminó de disolver el vínculo. El nombre del que la familia recuerda está anotado en la investigación, fuera del sitio público: es una persona viva que no eligió estar acá.\n\nSi esas cartas se guardaron en alguna caja, llevan remitente y dirección. Eso sería más que cualquier acta.",
  f:[["Nacimiento","6 de septiembre de 1925, Mar del Plata","Libreta de Familia, acta n. 1026."],
     ["Casada con","Un Durán"],
     ["La pista","Se carteaba con parientes D'Ortona en Messina","Recuerdo familiar, sin confirmar. Es el único indicio de un comune concreto para el apellido de su madre."]],
  img:[["registros/libreta-familia-olga-elda.jpg","Libreta de Familia: Olga Beatriz Angela (1922-1923) y Elda Angélica (1925)."]],
  docs:[["Acta de nacimiento","Mar del Plata, 6-sep-1925, acta n. 1026","tengo"],
        ["Acta de matrimonio","Con un Durán, lugar y fecha sin determinar","pedir"]],
  c:[["Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913","Elda Angélica, nació el 6 de Setiembre 1925 en Mar del Plata, acta n. 1026"],
     ["Testimonio familiar, 24 de agosto de 2026","se carteaba con familiares creo que en Messina"]]},
carmenCarlini:{nac:["ar"],zn:"Mar del Plata",n:"Carmen Carlini d'Ortona",d:"1914",b:"arg",pa:["franciscoCarlini","adelinaDortona"],
  note:"La mayor de los cuatro. Nació el 31 de marzo de 1914 en Mar del Plata y la bautizaron el 2 de agosto del mismo año, a los cuatro meses — como correspondía, y a diferencia de su hermano, cuyo bautismo esperó cuatro años y medio y por eso salió con el año equivocado.\n\nSus padres se habían casado en Buenos Aires diez meses antes, el 21 de mayo de 1913. Nació con la familia recién llegada a Mar del Plata.",
  f:[["Nacimiento","31 de marzo de 1914, Mar del Plata"],
     ["Bautismo","2 de agosto de 1914, Santa Cecilia, Mar del Plata"],
     ["Nombre como fue escrito","Carmen Carlini d'Ortona"]],
  img:[["registros/libreta-familia-defuncion-hijos.jpg","Libreta de Familia: los nacimientos de Carmen (1914) y José Francisco Calixto (1916), anotados por el Registro Civil."]],
  docs:[["Acta de nacimiento","Mar del Plata, 31-mar-1914","tengo"],
        ["Acta de bautismo","Mar del Plata, Santa Cecilia, 2-ago-1914","online"]],
  c:[["Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913","Doña Carmen, nació el 31 de Marzo 1914 en Mar del Plata"],
     ["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Santa Cecilia, Mar del Plata"]]},
olgaCarlini:{nac:["ar"],zn:"Mar del Plata",zm:"Mar del Plata",n:"Olga Beatriz Angela Carlini",d:"1922 – 1923",b:"arg",pa:["franciscoCarlini","adelinaDortona"],
  note:"La tercera, y la que nadie recordaba. Nació en Mar del Plata en agosto de 1922, acta n. 861, y MURIÓ EL 6 DE DICIEMBRE DE 1923, acta n. 493, con poco más de un año.\n\nSu segundo nombre, Beatriz, reaparece una generación después en Beatriz Carlini — la hermana de Aníbal, y justamente quien conservó esta libreta y la trajo el 24 de agosto de 2026.",
  f:[["Nacimiento","Agosto de 1922, Mar del Plata","Acta n. 861. El día quedó ilegible bajo el sello."],
     ["Defunción","6 de diciembre de 1923, Mar del Plata","Acta n. 493. Poco más de un año de vida."]],
  img:[["registros/libreta-familia-olga-elda.jpg","Libreta de Familia: Olga Beatriz Angela (1922-1923) y Elda Angélica (1925)."]],
  docs:[["Acta de nacimiento","Mar del Plata, agosto de 1922, acta n. 861","tengo"],
        ["Acta de defunción","Mar del Plata, 6-dic-1923, acta n. 493","tengo"]],
  c:[["Libreta de Familia, Registro Civil de la Capital, Buenos Aires, 1913","Olga Beatriz Angela, nació el de Agosto 1922 en Mar del Plata, acta n. 861 — falleció el 6 de Diciembre 1923, acta n. 493"]]},
haydee:{nac:["ar"],zn:"Mar del Plata",docs:[["Acta de nacimiento","General Pueyrredón, 4-mar-1925, acta n. 250 — traducción pública de 2008","tengo"],["Acta de defunción","Registro Civil, 2018","pedir"]],n:"Haydée Fichera",d:"1925 – 2018",b:"arg",pa:["antoninoF","carmelaV"],
  note:"Nació en la casa de Bolívar y Neuquén, en Mar del Plata, a las diez de la mañana del 25 de febrero de 1925. La inscribió su padre nueve días después.\n\nEl árbol la daba por nacida en Sicilia y suponía que la habían anotado AGATA, por la abuela, con el bautismo pendiente «a nombre de Agata». Las dos cosas eran falsas, y el acta las corrige de una sola pasada: nació acá, y se llamó Haydeé desde el día uno.\n\nLo interesante es que la costumbre siciliana sí operó. En esa misma acta la abuela figura como «Haydeé Castorina» — la que el árbol tiene como AGATA Castorina. A la nieta le pusieron el nombre de la abuela; lo que estaba mal era suponer con qué nombre se la conocía en la Argentina.",
  f:[["Nacimiento","25 de febrero de 1925, 10:00 — Bolívar y Neuquén, Mar del Plata","Acta n. 250 de General Pueyrredón, labrada el 4 de marzo de 1925.",1],
     ["Nombre inscripto","Haydeé","Tal cual, desde el nacimiento. Se cae la hipótesis de «Agata Fichera»."],
     ["Muerte","2018","Perfil familiar de FamilySearch; sin acta todavía."]],
  c:[["General Pueyrredón, 4-mar-1925, acta n. 250","«é NATA una creatura di sesso femminile alla quale le si é imposto il nome di HAYDEÉ; figlia legittima del dichiarante e di sua sposa Carmela Vaccaro»"],
     ["Testimonio de Juan Lucero, 23-ago-2026"],
     ["FamilySearch Family Tree, perfil G4X3-TGG"]]},
luigi:{nac:["it"],zn:"Latisana",zm:"Bella Vista",docs:[["Acta de nacimiento","Latisana 1929, Nati, Parte I, n. 130","tengo"],["Acta de matrimonio","San Giorgio di Nogaro 1953, Parte II Serie A n. 9","tengo"],["Lista di leva","Latisana, classe 1929","tengo"],["Certificado CNE","Cámara Nacional Electoral, n. 23481/2013","tengo"],["Acta de defunción","Bella Vista, 7-feb-2021","tengo"],["Copia integrale del nacimiento","Comune di Latisana — con las anotaciones al margen","pedir"]],pr:"Mecánico",n:"Luigi (Luis) Novello",d:"1929 – 2021",b:"friuli",pa:["giovanniN","idaM"],dc:1,
  note:"El dante causa de la ciudadanía italiana. Nunca se naturalizó argentino, y eso es exactamente lo que mantiene intacta la línea iure sanguinis hasta Federico y Antonio.",
  f:[["Nacimiento","28 de julio de 1929, 20:45 — Latisana (UD)","Aceptada sobre el 31 de julio de la sentencia de Trieste: cinco actos concordantes contra una transcripción judicial.",1],
     ["Bautismo","16 de octubre de 1929"],["Oficio","Meccanico (1953) · jubilado (2021)"],
     ["Servicio militar","Classe 1929, Comune di Latisana"],
     ["Residencia","Las Heras y Lafinur, Bella Vista — 1953"],
     ["Nacionalidad","Italiana, nunca naturalizado argentino"],
     ["Defunción","7 de febrero de 2021, Bella Vista"]],
  c:[["Latisana 1929, Nati, Parte I, n. 130","nato il 28 luglio 1929 alle ore 20:45"],
     ["Latisana 1948, Lista di leva","Novello Luigi, di Giovanni e Morello Ida"],
     ["CNE, certificado 23481/2013"]]},
liliana:{nac:["it"],zn:"Latisana",zm:"Bella Vista",docs:[["Acta de nacimiento","Latisana 1929, Nati, Parte I, n. 184","tengo"],["Acta de matrimonio","San Giorgio di Nogaro 1953, Parte II Serie A n. 9","tengo"],["Certificado CNE","Cámara Nacional Electoral, n. 23480/2013","tengo"],["Acta de defunción","Bella Vista, 11-jun-2017","tengo"],["Copia integrale del nacimiento","Comune di Latisana","pedir"]],pr:"Ama de casa",n:"Liliana De Faccio",d:"1929 – 2017",b:"friuli",pa:["gbD","santaC"],
  f:[["Nacimiento","4 de octubre de 1929, 23:00 — Latisana (UD)","La notificación parroquial dice 5 de octubre. Manda el acta civil.",1],
     ["Bautismo","28 de octubre de 1929"],["Oficio","Casalinga (1953) · jubilada (2017)"],
     ["Residencia","San Giorgio di Nogaro (UD) — 1953"],
     ["Nacionalidad","Italiana, nunca naturalizada argentina"],
     ["Defunción","11 de junio de 2017, Bella Vista, a los 87 años"]],
  c:[["Latisana 1929, Nati, Parte I, n. 184","nata il 4 ottobre 1929 alle ore 23:00"],
     ["CNE, certificado 23480/2013"]]},

giovanniN:{nac:["it"],docs:[["Acta de nacimiento","Comune di Latisana o Tribunale di Udine, ~1902","pedir"],["Lista di leva","Archivio di Stato di Udine, classe 1902","pedir"],["Acta de defunción","Registro Provincial PBA — Gral. Sarmiento / San Miguel, 1954-1985","pedir"]],pr:"Zapatero",img:[["registros/latisana-matrimonios-1892-1901-sin-novello.jpg","Matrimonios 1892-1901: el indice salta de Neri a Odorico. Sin Novello."],["registros/latisana-nacimientos-1892-1901-sin-novello.jpg","Nacimientos 1892-1901: salta de Neri a Olivier. Tampoco."]],url:"https://antenati.cultura.gov.it/ark:/12657/an_ua15621743",n:"Giovanni Novello",d:"~1902",b:"friuli",open:1,
  note:"FRONTERA. Descartado en Latisana revisando página por página los índices decenales, y en toda la provincia de Udine. La pista del Véneto se confirmó en el lugar correcto: hay familias Novello en Portogruaro, el comune que está cruzando el Tagliamento a cinco kilómetros de Latisana. Pero ningún Giovanni de ~1902 figura ahí tampoco, y el candidato más tentador —un Giovanni Giuseppe nacido en Venezia el 4 de septiembre de 1902— queda eliminado por su propia acta: murió en 1909, de siete años. Y conviene dudar de la edad: los 52 años salen de una declaración de 1954, y las edades declaradas son notoriamente aproximadas.",
  f:[["Nacimiento","~1902","Derivado: declarado de 52 años como testigo en agosto de 1954."],
     ["Oficio","Zapatero"],["Nacionalidad","Italiana"],["Residencia","Bella Vista, 1954"]],
  c:[["Bella Vista 1954, Nacimientos, acta n. 166","Juan Novello, 52 años, italiano, zapatero"]]},
idaM:{img:[["registros/latisana-matrimonios-1892-1901-morello.jpg","Latisana, indice decenal de matrimonios 1892-1901. Los ocho matrimonios Morello de la columna izquierda."]],url:"https://antenati.cultura.gov.it/ark:/12657/an_ua15617238",n:"Ida Morello",d:"?",b:"friuli",open:1,pa:["ferdinandoM","mariaZ"],hyp:1,
  note:"FRONTERA. Candidata única sin confirmar: la Ida Morello nacida el 23 de septiembre de 1895 en Codroipo, hija de Ferdinando Morello y Maria Zanin — es la única Ida Morello indexada en toda la provincia de Udine. En contra: sería siete años mayor que Giovanni. Ojo — en Latisana conviven MORELLO y MURELLO como apellidos distintos: no colapsarlos.",
  f:[["Los Morello sí son de Latisana","Ocho matrimonios Morello en el decenio 1892-1901: Anna (1892, acta 2) · Bernardo (1901, 1) · Carolina (1893, 27) · Francesco (1900, 9) · Giovanni (1896, 21) · Luigi (1897, 26) · Maria (1899, 26) · Teresa (1895, 21).","Entre esos ocho puede estar el matrimonio de los padres de Ida. Hipótesis de trabajo: Giovanni Novello llegó de afuera y se casó con una Morello local."]],
  c:[["Latisana 1948, Lista di leva","di Giovanni e Morello Ida"],
     ["Latisana 1892-1901, Matrimoni, indici decennali, segn. 6520"]]},
gbD:{docs:[["Acta de nacimiento","Comune di San Giorgio di Nogaro o Latisana","pedir"]],n:"Giovanni Battista De Faccio",d:"?",b:"friuli",open:1,
  note:"FRONTERA, y la friulana más resistente. Los 514 De Faccio indexados en la provincia de Udine se concentran en Udine ciudad y en Premariacco/Ipplis — no en la Bassa Friulana, que es donde vivía esta familia.",
  f:[["Variantes del nombre","Giobatta · Gio Batta · Juan Bautista"],
     ["Núcleos De Faccio hallados en Udine","Pietro De Faccio × Teresa del Torre · Angelo De Faccio × Domenica Molinari (Ipplis) · Luigi De Faccio × Amabile Morandini · Giuseppe De Faccio × Giuseppina Cattarossi","Ninguno pudo vincularse a Giovanni Battista. Son homónimos de otra zona de la provincia."],
     ["Por qué es difícil","San Giorgio di Nogaro perdió casi todo su archivo comunal anterior a 1918 en la invasión de Caporetto, y no tiene índices decenales de nacimientos en Antenati en ningún decenio.","Sobrevivieron las segundas copias del Tribunale (325 registros) y los libros parroquiales, que no eran del comune. Hay que rutear por el Archivio di Stato y la parroquia, nunca por el comune."],
     ["Trampa técnica","En los índices, «DE FACCIO» puede estar alfabetizado bajo D o bajo F. Hay que revisar las dos."]],
  c:[["San Giorgio di Nogaro 1953, Matrimoni, Parte II Serie A, n. 9","figlia di Giovanni Battista e Cagnolini Santa"],
     ["FamilySearch, Udine 1806-1815 y 1871-1911: 514 registros De Faccio revisados"]]},
santaC:{docs:[["Acta de nacimiento","Comune di Latisana, ~1900","pedir"]],n:"Santa Cagnolini",d:"?",b:"friuli",open:1,pa:["giuseppeEM"],hyp:1,
  note:"FRONTERA, pero la más cerca de caer. Los Cagnolini son de Latisana y hay tres generaciones reconstruidas. La hipótesis onomástica es fuerte: por la costumbre italiana, una nieta de Santa Pinzani nacida hacia 1900 se habría llamado Santa Cagnolini. El padre más probable es Giuseppe Enrico Marzio, que tendría 20 años en 1900.",
  f:[["Variante del nombre","Santina — y «Cagnolin» en el acta de Patricia"],
     ["Qué falta","Su acta de nacimiento, ~1895-1905, en el Comune di Latisana","Cae después de 1900, donde termina Antenati: no está online, hay que pedirla."]],
  c:[["San Giorgio di Nogaro 1953, Matrimoni, Parte II Serie A, n. 9","figlia di Giovanni Battista e Cagnolini Santa"]]},

antoninoF:{nac:["it"],zn:"Catania",docs:[["Acta de matrimonio","General Pueyrredón, 1918, folio 12","tengo"],["Acta de nacimiento","Provincia de Catania, ~1895-1899","pedir"],["Acta de defunción","General Pueyrredón, antes de feb-1967","pedir"]],pr:"Obrero de la construcción · dirigente gremial",n:"Antonino Fichera",d:"1898",b:"sicilia",pa:["giovanniF","agataC"],
  note:"Lleva el nombre de su abuelo materno, Antonino Castorina — la regla siciliana del segundo varón.",
  f:[["Nacimiento","1898, provincia de Catania","El acta de matrimonio de 1918 lo hace «natural de la provincia de Cattania». Pero las edades no cierran: 23 años en 1918 daría ~1895, y 26 en 1925 daría ~1899. Se mantiene 1898 y se anotan las dos lecturas: hay que pedir el acta en Catania."],
     ["Confirmación","14 de febrero de 1908, Diócesis de Acireale"],
     ["Matrimonio","General Pueyrredón, folio 12 — el año no está resuelto","Con Carmela Vaccaro, los dos solteros. Testigo, su hermano Rosario, panadero. La boleta dice 1918; las tres edades declaradas dan 1921-22."],
     ["Oficio al casarse","Pescador","Acta del folio 12, en la copia buena. La copia velada se había leído «jornalero». Después vino la construcción y el gremio."],
     ["Llegada","22 de marzo de 1909, en el buque France desde Génova","Con la familia, de unos 10-11 años. El certificado de CEMLA es de su hermano Rosario, que viajó a los 12."],
     ["Muerte","Antes de febrero de 1967","Su mujer figura VIUDA en el acta de defunción de ella, del 9 de febrero de 1967."],
     ["Emigración","Embarcó solo en Génova; su mujer lo siguió dos años después. Buque recordado como «Francia».","El buque no pudo confirmarse en la bibliografía de la ruta: sirve para confirmar un candidato, nunca para descartar."],
     ["Oficio","Construcción; dirigente gremial en Mar del Plata"],
     ["Muerte","Accidente de obra: le cayó un ascensor. La familia sostenía que lo habían matado."]],
  sib:["rosarioH","antoninaF","mariaF","giuseppe2"],
  c:[["General Pueyrredón, matrimonio, folio 12 — copia legible","«Antonio Fichera de veintitrés años, italiano, natural de la Provincia de Cattania, domiciliado en esta ciudad, soltero, pescador, hijo de don Juan Fichera, pescador, y de Doña Haydeé Castorino»"],
     ["Al margen del mismo folio, Dirección General del Registro Provincial de las Personas","«el verdadero nombre de la madre del contrayente es: AGATA CASTORIN[A]»"],
     ["Diocesi di Acireale, confirmación 14-feb-1908"],["Testimonio de Juan Lucero, 23-ago-2026"]]},
veneraF:{nac:["ar"],zn:"Mar del Plata",n:"Venera Fichera",d:"1911",b:"arg",pa:["giovanniF","agataC"],
  note:"La prueba onomástica más limpia de todo el árbol, y encima llegó sola. La costumbre siciliana manda que la segunda hija lleve el nombre de la abuela materna, y la abuela materna era VENERA PRIVITERA. El nombre estaba predicho antes de encontrar el acta. Nació el 6 de julio de 1911 y la bautizaron el 8 de octubre en la Catedral de Mar del Plata: el indexador leyó a la madre como «Angela Castorino» en esta acta y como «Agueda Castorino» en la de su hermano — Agueda es Águeda, o sea Agata.",
  f:[["Nacimiento","6 de julio de 1911, Mar del Plata"],
     ["Bautismo","8 de octubre de 1911, Catedral de los Santos Pedro y Cecilia"],
     ["Por qué se llama así","Por su abuela materna, Venera Privitera","La regla onomástica siciliana lo predecía."]],
  c:[["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Catedral, Mar del Plata","Venera Fichera, nacida 6 de julio de 1911, hija de Juan Fichera y Angela Castorino"]]},
salvadorF:{nac:["ar"],zn:"Mar del Plata",n:"Salvador Fichera",d:"1910",b:"arg",pa:["giovanniF","agataC"],
  note:"El primer Fichera del que consta que nació en la Argentina, y por eso mueve toda la cronología de la rama: si lo bautizaron en Mar del Plata en agosto de 1910, la familia ya estaba instalada acá. Su acta es además la que escribe a la madre como «Agueda Castorino» — Águeda, o sea Agata.",
  f:[["Nacimiento","2 de febrero de 1910, Mar del Plata"],
     ["Bautismo","14 de agosto de 1910, Santa Cecilia, Mar del Plata"]],
  c:[["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Santa Cecilia, Mar del Plata","Salvador Fichera Castorino, nacido 2 de febrero de 1910, hijo de Juan Fichera y Agueda Castorino"]]},
carmelaV:{nac:["it"],zn:"Messina",zm:"Mar del Plata",docs:[["Acta de matrimonio","General Pueyrredón, 1918, folio 12","tengo"],["Acta de nacimiento de su hija Haydeé","General Pueyrredón, 4-mar-1925, acta n. 250","tengo"],["Acta de defunción","Mar del Plata, 9-feb-1967, acta n. 2·1 T.º 1.º","tengo"],["Acta de nacimiento","Italia, 20-oct-1899 — empezar por Catania y Messina","pedir"]],n:"Carmela Vaccaro",d:"1899 – 1967",b:"sicilia",pa:["antonioVac","pancraciaDB"],
  note:"Hasta el 24 de agosto de 2026 era una frontera: un nombre suelto, sin fechas y sin padres, sostenido nada más que por el testimonio oral. Dos actas la cerraron el mismo día.\n\nY las dos coinciden en lo que importa. En 1925 declara 25 años y se la anota hija de Antonio Vaccaro y Pancracia Di Bella; en 1967 el acta de defunción le da 67 años, la hace nacer el 20 de octubre de 1899 en Italia, y nombra a los mismos dos padres. Cuarenta y dos años separan un documento del otro, se labraron por motivos distintos y los declarantes fueron personas distintas: que den los mismos dos nombres no es un eco, son dos testimonios independientes.\n\nMurió a los 67 años en la vía pública, en Colón y las vías del ferrocarril, de hundimiento de cráneo y traumatismos varios. Intervino la policía. Vivía en Bolívar 1678 y estaba viuda.",
  f:[["Nacimiento","20 de octubre de 1899, provincia de MESSINA","La fecha, del acta de defunción de 1967. La provincia, del acta de matrimonio de 1918: «natural de la provincia de Messina». El testimonio oral la hacía de Acireale, que es Catania — le gana el documento al recuerdo.",1],
     ["Matrimonio","General Pueyrredón, folio 12 — el año no está resuelto","Con Antonio Fichera, los dos solteros. La boleta del archivo dice 1918, pero declara VEINTIDÓS años: nacida en octubre de 1899, eso da 1921-22. Y las edades de él (23) y del testigo Rosario (25) apuntan al mismo lado."],
     ["Muerte","9 de febrero de 1967, 8:00 — Colón y las vías del ferrocarril, Mar del Plata","Hundimiento de cráneo y traumatismos varios. Certificó el Dr. Carlos Bignone."],
     ["Domicilio","Bolívar y Neuquén (1925) · Bolívar 1678 (1967)"],
     ["Estado al morir","Viuda de Antonio Fichera","Es el primer límite superior que tenemos para la muerte de él."],
     ["Documentos","Sin documentos","Así consta en el acta de defunción: nunca tramitó C.I. argentina."]],
  c:[["General Pueyrredón, matrimonio, folio 12 — copia legible","«Doña Carmela Vaccaro, soltera, de veintidós años, italiana, natural de la Provincia de Messina, domiciliada en esta ciudad, hija de Don Antonino Vaccaro, pescador, y de Doña Pancracia di Bella, ambos italianos, domiciliados en esta ciudad»"],
     ["General Pueyrredón, 4-mar-1925, acta n. 250","«Carmela Vaccaro di anni venticinque, italiana… figlia di Antonio Vaccaro e Pancracia Di Bella»"],
     ["Mar del Plata, 9-feb-1967, defunción","«de 67 años, estado viuda de Antonio Fichera… nacido el 20/10/1899 en Italia, hija de Antonio Vaccaro y de Pancracia Di Bella»"],
     ["Testimonio de Juan Lucero, 23-ago-2026"]]},
antonioVac:{pr:"Pescador",n:"Antonino Vaccaro",d:"?",b:"sicilia",open:1,
  f:[["Oficio","Pescador","Acta de matrimonio de su hija. Viniendo de Messina, que es costa, y llegando a Mar del Plata: el oficio viajó con él."],
     ["En Mar del Plata","Al menos al casarse su hija","El acta lo pone «domiciliado en esta ciudad»: emigró él también."],
     ["Origen","Provincia de Messina","Derivado del de su hija Carmela, que el acta declara natural de esa provincia."],
     ["Nombre","Antonino, no Antonio","La primera copia del acta —velada— se leyó «Antonio». La copia buena dice ANTONINO. Las actas de 1925 y 1967 lo escriben Antonio."]],
  note:"Padre de Carmela Vaccaro. Entra al árbol el 24 de agosto de 2026 por dos actas independientes que lo nombran igual: el nacimiento de su nieta Haydeé en 1925 y la defunción de su hija en 1967.\n\nNo se sabe nada más de él todavía. El camino para seguir es el acta de nacimiento de Carmela, del 20 de octubre de 1899 — que además diría de qué comune salió la familia.",
  c:[["General Pueyrredón, 4-mar-1925, acta n. 250"],
     ["Mar del Plata, 9-feb-1967, defunción de Carmela Vaccaro"]]},
pancraciaDB:{n:"Pancracia Di Bella",d:"?",b:"sicilia",open:1,
  f:[["En Mar del Plata","Al menos al casarse su hija","Igual que su marido: «domiciliada en esta ciudad» en el acta de matrimonio."],
     ["Origen","Provincia de Messina","Derivado del de su hija Carmela."]],
  note:"Madre de Carmela Vaccaro. Mismas dos actas que su marido.\n\nEl nombre ayuda a ubicar la rama: DI BELLA se concentra en Messina y Catania, y Pancrazia es una devoción local, no un nombre de uso general. Los dos apuntan al mismo tramo de la costa jónica donde ya están los Fichera de Giarre y los Castorina de Acireale.",
  c:[["General Pueyrredón, 4-mar-1925, acta n. 250"],
     ["Mar del Plata, 9-feb-1967, defunción de Carmela Vaccaro"]]},
giovanniF:{nac:["it"],zn:"Giarre",docs:[["Acta de matrimonio","Acireale 1895, Matrimoni, atto n. 99","online"],["Acta de nacimiento","Giarre, 2-jul-1869 — Catania, Stato Civile 1820-1900","online"]],pr:"Bracciante — jornalero del campo",url:"https://www.familysearch.org/ark:/61903/1:1:XWT7-4LC4",n:"Giovanni Fichera",d:"1869",b:"sicilia",pa:["rosarioF","mariaB"],
  note:"El testimonio oral decía Giarre, jornalero del campo, casado con una Castorina de Acireale. El acta de 1895 lo confirma palabra por palabra.\n\nY el 24 de agosto de 2026 apareció el otro extremo de su vida: en Mar del Plata bautizó a dos hijos, Salvador en agosto de 1910 y Venera en octubre de 1911, y en las dos actas figura como «Juan Fichera». O sea que la familia ya estaba instalada en Argentina EN 1910 — diez años antes de lo que suponía el relato familiar, que hablaba de un cruce alrededor de 1920. Las dos cosas pueden ser ciertas si el que cruzó en los años veinte fue Antonino, ya adulto y por su cuenta; pero la fecha de llegada de sus padres hay que correrla una década para atrás.",
  f:[["Nacimiento","2 de julio de 1869, Giarre (Catania)","Fecha exacta del acta civil de nacimiento. Antes sólo se tenía el año, derivado de los 26 declarados en 1895."],
     ["Oficio","Bracciante — jornalero del campo"],
     ["Matrimonio","25 de julio de 1895, Acireale"],
     ["En Mar del Plata","Al menos desde febrero de 1910","Bautizó a su hijo Salvador en Santa Cecilia en agosto de ese año."],
     ["Nombre en Argentina","Juan Fichera"],
     ["Oficio en Argentina","Pescador","En Sicilia era bracciante — jornalero del campo. El acta de matrimonio de su hijo lo pone PESCADOR: al llegar a un puerto, la familia entera pasó al mar."],
     ["Llegada","22 de marzo de 1909, buque France, desde Génova","Fecha del certificado de CEMLA de su hijo Rosario, de 12 años. Encaja con el bautismo de Salvador en Mar del Plata en febrero de 1910."]],
  c:[["Acireale 1895, Matrimoni, atto n. 99","Giovanni Fichera, anni 26, nato a Giarre, bracciante"],
     ["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Mar del Plata","Salvador Fichera Castorino (1910) y Venera Fichera (1911), hijos de Juan Fichera"]]},
agataC:{nac:["it"],zn:"Acireale",docs:[["Acta de matrimonio","Acireale 1895, Matrimoni, atto n. 99","online"]],url:"https://www.familysearch.org/ark:/61903/1:1:XWT7-4LC4",n:"Agata Castorina",d:"~1873",b:"sicilia",pa:["antoninoC","veneraP"],
  note:"Su nieta Haydée probablemente fue bautizada Agata en su honor — y ahora se ve que el nombre venía viajando con ella. En los registros de Mar del Plata aparece castellanizada de dos maneras distintas por dos indexadores distintos: «Agueda Castorino» en el bautismo de su hijo Salvador y «Angela Castorino» en el de su hija Venera. Agueda es Águeda, que es como se traduce Agata. Y su hijo mayor, Rosario, le puso Yolanda AGUEDA a su primera hija en 1919.",
  f:[["Nacimiento","~1873, Acireale","Derivado de la edad declarada — 22 años — en julio de 1895."],
     ["En Mar del Plata","Al menos desde 1910"],
     ["Nombre en Argentina","Haydeé Castorino — y rectificado","Dos actas civiles la escriben HAYDEÉ: el matrimonio de su hijo Antonio y el nacimiento de su nieta en 1925. Pero al margen del acta de matrimonio hay una resolución de la Dirección General del Registro Provincial de las Personas: «el verdadero nombre de la madre del contrayente es AGATA CASTORIN[A]». O sea que Haydeé era el nombre de uso, y como nombre legal fue un error que la familia hizo corregir — casi seguro para que los papeles argentinos coincidieran con los italianos. A la nieta igual le pusieron Haydeé."],
     ["Otras formas","Agueda Castorino (1910) · Angela Castorino (1911)","Dos lecturas distintas del mismo nombre en dos actas de la misma parroquia."]],
  c:[["Acireale 1895, Matrimoni, atto n. 99","Agata Castorina, anni 22, di Acireale"],
     ["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Mar del Plata"]]},
rosarioF:{nac:["it"],zn:"Giarre",docs:[["Acta de matrimonio","Giarre, 15-nov-1852","online"]],pr:"Bracciante",n:"Rosario Fichera",d:"1828 – ?",b:"sicilia",pa:["cirinoF","nunziaMus"],
  note:"Durante meses fue el techo de esta rama, y por una razón buena: en Acireale y Giarre hay cinco Rosario Fichera contemporáneos, cada uno con padres distintos, y colgarle los padres del equivocado habría sido peor que dejar el árbol corto. Lo que lo destrabó no fue encontrar un Rosario más, sino atacar la identificación por el otro lado: por la PAREJA. Rosario Fichera casado con Maria Bonaventura, en Giarre, es uno solo.\n\nY después la aritmética cerró sola. El acta de nacimiento de su hijo Giovanni, del 2 de julio de 1869, le da al padre CUARENTA Y UN AÑOS y a la madre TREINTA Y SEIS: eso da 1828 y 1833, exactamente los años del matrimonio celebrado en Giarre el 15 de noviembre de 1852. Tuvieron once hijos.",
  f:[["Nacimiento","1828, Giarre (Catania)"],
     ["Matrimonio","15 de noviembre de 1852, Giarre"],
     ["Hijos","Once — seis varones y cinco mujeres"],
     ["Cómo se lo identificó","Por la pareja, no por el nombre","Rosario Fichera hay cinco; Rosario Fichera casado con Maria Bonaventura en Giarre, uno."]],
  c:[["Acireale 1895, Matrimoni, atto n. 99","padre del novio Giovanni Fichera"],
     ["Catania, Stato Civile (Archivio di Stato) 1820-1900 — nacimiento de Giovanni Fichera, 2 de julio de 1869","padre de 41 años, madre de 36"],
     ["FamilySearch Family Tree, perfil G367-CX4 — 39 fuentes adjuntas"]]},
cirinoF:{nac:["it"],zn:"Giarre",pr:"Bracciante",n:"Cirino Fichera",d:"1803 – ant. 1852",b:"sicilia",open:1,
  note:"Padre de Rosario, y la confirmación llega por donde siempre: por los nombres. La regla siciliana manda que el primer varón lleve el nombre del abuelo paterno, y el primer hijo de Rosario, nacido en 1853, se llamó CIRINO. Cirino no es un nombre cualquiera — es la forma siciliana de Ciro, muy de la zona del Etna, y no se elige por casualidad. Ya había muerto cuando su hijo se casó, en noviembre de 1852. Con Nunzia Musumeci tuvo once hijos, siete varones y cuatro mujeres.",
  f:[["Nacimiento","1803, Giarre"],
     ["Muerto antes de","noviembre de 1852"],
     ["Hijos","Once, con Nunzia Musumeci"],
     ["Confirmación onomástica","Su nieto mayor se llamó Cirino, nacido en 1853"]],
  c:[["FamilySearch Family Tree, perfil G8S5-YNK — 43 fuentes adjuntas","Catania, Stato Civile (Archivio di Stato) 1820-1900 y Stato Civile (Tribunale) 1866-1929"]]},
nunziaMus:{nac:["it"],zn:"Giarre",n:"Nunzia Musumeci",d:"1792 – ?",b:"sicilia",pa:["angeloMus","veneraFicheraM"],
  note:"Madre de Rosario, once años mayor que su marido. Y otra vez el nombre la confirma: la primera hija de Rosario, nacida en 1855, se llamó NUNZIA. La regla manda que la primera hija lleve el nombre de la abuela paterna, y ahí está.",
  f:[["Nacimiento","1792, Giarre"],
     ["Confirmación onomástica","Su nieta mayor se llamó Nunzia, nacida en 1855"]],
  c:[["FamilySearch Family Tree, perfil G8S5-T1Z — 43 fuentes adjuntas"]]},
angeloMus:{n:"Angelo Musumeci",d:"?",b:"sicilia",open:1,hyp:1,
  note:"Padre de Nunzia según el árbol colaborativo de FamilySearch, con sólo dos fuentes adjuntas — las dos del estado civil de Catania 1820-1900. Es la capa más delgada de esta rama: se registra como hipótesis, no como dato.",
  c:[["FamilySearch Family Tree, perfil P7LL-6SZ — 2 fuentes adjuntas"]]},
veneraFicheraM:{n:"Venera Fichera",d:"?",b:"sicilia",open:1,hyp:1,
  note:"Madre de Nunzia Musumeci — y sí, Fichera otra vez: el apellido entra en la rama por los dos lados, cosa nada rara en pueblos del Etna donde media Giarre se apellidaba Fichera. No confundirla con Venera Fichera, la bisnieta nacida en Mar del Plata en 1911. Hipótesis: viene del árbol colaborativo, con soporte delgado.",
  c:[["FamilySearch Family Tree — vía el perfil de Nunzia Musumeci"]]},
mariaB:{nac:["it"],zn:"Giarre",zm:"Riposto",docs:[["Acta de defunción","Riposto, 3-dic-1912, acta n. 168","online"]],pr:"Casalinga",n:"Maria Bonaventura",d:"1833 – 1912",b:"sicilia",pa:["rosarioBon","angelaMur"],
  note:"Nacida en Giarre en 1833, casada a los diecinueve el 15 de noviembre de 1852, madre de once hijos y viuda al final: murió el 3 de diciembre de 1912 en Riposto, a los ochenta y tres años, y el acta la anota como CASALINGA. Es el acta que permitió llegar a sus padres.",
  f:[["Nacimiento","1833, Giarre"],
     ["Matrimonio","15 de noviembre de 1852, Giarre"],
     ["Oficio","Casalinga"],
     ["Defunción","3 de diciembre de 1912, Riposto (Catania), a los 83 años","Acta n. 168."]],
  c:[["Acireale 1895, Matrimoni, atto n. 99","madre del novio Giovanni Fichera"],
     ["Catania, Stato Civile (Tribunale) 1866-1929 — defunción, Riposto, 3-dic-1912, acta n. 168","Maria Bonaventura, anni 83, nata a Giarre, casalinga, moglie di Rosario Fichera"],
     ["FamilySearch Family Tree, perfil G367-SD6 — 40 fuentes adjuntas"]]},
rosarioBon:{nac:["it"],zn:"Giarre",zm:"Giarre",pr:"Bracciante",n:"Rosario Bonaventura",d:"1806 – 1851",b:"sicilia",pa:["micheleBon","mariaLeotta"],
  note:"Padre de Maria. Se casó con Angela Murano el 8 de noviembre de 1830 en Giarre y murió ahí mismo el 21 de julio de 1851, a los cuarenta y seis — o sea que no llegó a ver casarse a su hija, apenas un año después. La regla onomástica lo confirma desde el otro extremo: el segundo varón de Maria, nacido en 1857, se llamó ROSARIO, que es lo que manda la costumbre para el abuelo materno.",
  f:[["Nacimiento","~1806, Giarre"],
     ["Matrimonio","8 de noviembre de 1830, Giarre"],
     ["Defunción","21 de julio de 1851, Giarre, a los 46 años"],
     ["Confirmación onomástica","Su nieto segundo se llamó Rosario, nacido en 1857"]],
  c:[["FamilySearch Family Tree, perfil GDSX-F1C — 38 fuentes adjuntas"]]},
angelaMur:{nac:["it"],zn:"Giarre",zm:"Giarre",n:"Angela Murano",d:"~1808 – 1878",b:"sicilia",pa:["rosarioMar","caterinaPan"],
  note:"Madre de Maria. Murió en Giarre el 24 de julio de 1878, a los setenta y uno. El apellido baila entre MURANO y MARANO según el acta — en el acta de defunción de su hija, de 1912, el indexador lo leyó Marano. Y otra vez los nombres cierran: la segunda hija de Maria, nacida en 1859, se llamó ANGELA, que es lo que la costumbre reserva para la abuela materna.",
  f:[["Nacimiento","~1808, Giarre"],
     ["Matrimonio","8 de noviembre de 1830, Giarre"],
     ["Defunción","24 de julio de 1878, Giarre, a los 71 años"],
     ["Variantes","Murano · Marano"],
     ["Confirmación onomástica","Su nieta segunda se llamó Angela, nacida en 1859"]],
  c:[["FamilySearch Family Tree, perfil GDSX-K5B — 16 fuentes adjuntas"]]},
micheleBon:{n:"Michele Bonaventura",d:"~1774",b:"sicilia",open:1,hyp:1,
  note:"Padre de Rosario Bonaventura según el árbol colaborativo, con seis fuentes adjuntas del estado civil de Catania. Capa delgada: hipótesis. No confundirlo con su nieto Michele Bonaventura, nacido en 1841.",
  c:[["FamilySearch Family Tree, perfil PHG1-ZQ7 — 6 fuentes adjuntas"]]},
mariaLeotta:{n:"Maria Leotta",d:"~1769",b:"sicilia",open:1,hyp:1,
  note:"Mujer de Michele Bonaventura. La persona más antigua de la rama siciliana, y también la más frágil: viene del árbol colaborativo, sin acta leída de primera mano. Hipótesis.",
  c:[["FamilySearch Family Tree, perfil PHGB-YF8"]]},
rosarioMar:{n:"Rosario Marano",d:"?",b:"sicilia",open:1,hyp:1,
  note:"Padre de Angela Murano según el árbol colaborativo. Su nombre explicaría, de paso, por qué el primer hijo de Rosario Bonaventura y Angela se llamaría Rosario. Hipótesis.",
  c:[["FamilySearch Family Tree — vía el perfil de Angela Murano"]]},
caterinaPan:{n:"Caterina Panebianco",d:"?",b:"sicilia",open:1,hyp:1,
  note:"Madre de Angela Murano según el árbol colaborativo. Panebianco es apellido muy de la zona del Etna. Hipótesis.",
  c:[["FamilySearch Family Tree — vía el perfil de Angela Murano"]]},
antoninoC:{nac:["it"],zn:"Acireale",zm:"Acireale",docs:[["Acta de defunción","Acireale 1905","online"],["Acta de matrimonio","Acireale 1860, registro parroquial","online"]],pr:"Bracciante",n:"Antonino Castorina",d:"1837 – 1905",b:"sicilia",pa:["salvatoreC","angelaM"],
  note:"CASTORINA es un apellido muy característico de Acireale. Su nieto Antonino Fichera lleva su nombre, por la regla siciliana del segundo varón.",
  f:[["Nacimiento","1837, Acireale"],
     ["Matrimonio","3 de junio de 1860, con Venera Privitera"],
     ["Defunción","22 de enero de 1905, Acireale"]],
  c:[["Acireale 1895, Matrimoni, atto n. 99"],
     ["Catania, Stato civile, defunción 22-ene-1905","Antonino Castorina, nato 1837 Acireale, di Salvatore e Angela Motta"],
     ["Diocesi di Acireale, matrimonio 3-giu-1860","figlio di Salvatore Castorina e Angilberga Motto"]]},
veneraP:{n:"Venera Privitera",d:"~1840",b:"sicilia",pa:["francescoP","agataL"],
  f:[["Matrimonio","3 de junio de 1860, Acireale"]],
  c:[["Acireale 1895, Matrimoni, atto n. 99"],
     ["Diocesi di Acireale, matrimonio 3-giu-1860","figlia di Francesco Privitera e Agata Leonardi"]]},
francescoP:{n:"Francesco Privitera",d:"~1815",b:"sicilia",
  note:"Hallado en el registro parroquial del matrimonio de su hija Venera, en 1860. Su nieto Francesco Castorina lleva su nombre, por la regla del segundo varón.",
  c:[["Diocesi di Acireale, matrimonio 3-giu-1860"]]},
agataL:{n:"Agata Leonardi",d:"~1818",b:"sicilia",
  note:"Hallada en el mismo registro de 1860. Su bisnieta Agata Castorina y su tataranieta Haydée (probablemente Agata) llevan su nombre: el nombre viaja cuatro generaciones seguidas por la rama femenina.",
  c:[["Diocesi di Acireale, matrimonio 3-giu-1860"]]},

/* ---- Hermanos de Agata Castorina ---- */
francescoCast:{n:"Francesco Castorina",d:"?",b:"sicilia",pa:["antoninoC","veneraP"],
  note:"Hermano de Agata. Su nombre viene del abuelo materno, Francesco Privitera.",
  c:[["Catania, Stato civile 1866-1929"]]},
salvatoreCast:{n:"Salvatore Castorina",d:"?",b:"sicilia",pa:["antoninoC","veneraP"],
  note:"Hermano de Agata. Su nombre viene del abuelo paterno, Salvatore Castorina. Que los dos hermanos lleven exactamente los nombres que la regla siciliana predice es una confirmación cruzada de toda la reconstrucción.",
  c:[["Catania, Stato civile 1866-1929"]]},
salvatoreC:{n:"Salvatore Castorina",d:"~1810",b:"sicilia",
  note:"Generación nueva, hallada por dos fuentes independientes: el acta de defunción civil de su hijo Antonino (1905) y el registro parroquial de su matrimonio (1860).",
  c:[["Catania, Stato civile, defunción de Antonino Castorina, 22-ene-1905"],
     ["Diocesi di Acireale, matrimonio de Antonino Castorina, 3-giu-1860"]]},
angelaM:{n:"Angela Motta",d:"~1812",b:"sicilia",
  note:"El registro parroquial la anota como «Angilberga Motto» y el civil como «Angela Motta»: la misma persona, dos grafías. Por su generación es la candidata natural a ser la antepasada de ~1812 a la que llegó Juan Lucero por su cuenta — sería una confirmación cruzada, pero está SIN VERIFICAR.",
  c:[["Catania, Stato civile, defunción de Antonino Castorina, 22-ene-1905","di Salvatore e Angela Motta"],
     ["Diocesi di Acireale, matrimonio 3-giu-1860","Angilberga Motto"]]},

/* ---- Hermanos de Giovanni Fichera ---- */
nuntiaF:{n:"Nuntia Fichera",d:"?",b:"sicilia",pa:["rosarioF","mariaB"],
  note:"Hermana de Giovanni. Aparece como novia en los registros parroquiales de la Diócesis de Acireale.",
  c:[["Diocesi di Acireale, Catholic Church Records 1560-1950"]]},
salvatoreF:{n:"Salvatore Fichera",d:"?",b:"sicilia",pa:["rosarioF","mariaB"],
  note:"Hermano de Giovanni. Aparece como novio en los registros parroquiales de la Diócesis de Acireale. Su nombre sugiere que la familia Fichera y la Castorina ya se cruzaban antes de 1895.",
  c:[["Diocesi di Acireale, Catholic Church Records 1560-1950"]]},
rosarioH:{docs:[["Certificado de arribo — CEMLA","n. 82083 · Buenos Aires, 22-mar-1909, buque France","tengo"]],pr:"Panadero",n:"Rosario Fichera",d:"~1896",b:"sicilia",pa:["giovanniF","agataC"],
  note:"Es, sin buscarlo, la persona que fechó la llegada de toda la rama siciliana. Su certificado de arribo del CEMLA dice: Génova, buque FRANCE, Buenos Aires, 22 de marzo de 1909, doce años.\n\nY con eso confirma el testimonio de Juan Lucero, que recordaba el barco como «Francia» — el árbol lo tenía anotado como un dato que servía para confirmar un candidato pero nunca para descartar. Era el France. Lo que el relato erraba es quién viajaba: no fue Antonino solo y adulto, fue la familia entera con los hijos chicos.\n\nEstaba en el árbol como hipótesis —la regla onomástica manda que el primer varón lleve el nombre del abuelo paterno, y el abuelo paterno era Rosario Fichera— y el 24 de agosto de 2026 quedó documentado. En Mar del Plata bautizó dos hijas con Petronilla Bedetti: Yolanda AGUEDA, nacida el 8 de febrero de 1919, y Gioconda Elina, nacida el 15 de agosto de 1920. Que a la primera la llamara Agueda —Águeda, Agata— cierra el círculo: es el nombre de su propia madre, exactamente donde la costumbre lo pone.",
  f:[["Llegada","22 de marzo de 1909 a Buenos Aires, en el buque FRANCE desde Génova","Certificado de arribo n. 82083 del CEMLA. Doce años, soltero, sin profesión. Es la fecha exacta en que llegó la familia.",1],
     ["Edad al llegar","12 años","Da un nacimiento en 1896-1897, que es lo que ya suponía la regla onomástica."],
     ["Oficio","Panadero","Al ser testigo del casamiento de su hermano, viviendo en Bolívar e Italia."],
     ["Casado con","Petronilla (Petrolina) Bedetti"],
     ["Hijas","Yolanda Agueda (8-feb-1919) · Gioconda Elina (15-ago-1920)","Las dos bautizadas en Mar del Plata."]],
  c:[["CEMLA, certificado de arribo a América n. 82083","«ROSARIO FICHERA, de nacionalidad ITALIANA, procedente de GENOVA, llegó a BUENOS AIRES el 22 de Marzo de 1909 en el buque FRANCE. Edad: 12 años»"],
     ["Argentina, Buenos Aires, registros parroquiales 1635-2017 — Mar del Plata","Yolanda Agueda Fichera y Gioconda Elina Fichera Bedetti, hijas de Rosario Fichera y Petronilla Bedetti"]]},
antoninaF:{pa:["giovanniF","agataC"],n:"Antonina Fichera",d:"1898",b:"sicilia",
  note:"Bautizada el 15 de octubre de 1898, el mismo año que Antonino. O son mellizos, o el índice leyó mal el latín «Antoninus»."},
mariaF:{pa:["giovanniF","agataC"],n:"Maria Fichera",d:"1900",b:"sicilia"},
giuseppe2:{pa:["giovanniF","agataC"],n:"Giuseppe Fichera",d:"1904",b:"sicilia",
  note:"Un hermano anterior con el mismo nombre murió antes de cumplir el año, en 1903. Reutilizar el nombre era práctica habitual."},

/* ---- Hermanos de Liliana: por testimonio familiar, sin documento todavía ---- */
ivonne:{t:1,n:"Ivonne De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermana de Liliana. Sólo por testimonio familiar: no hay documento. «Ivonne» es la forma francesa de Yvonne — llamativa en el Friuli de entreguerras, porque el fascismo desalentaba los nombres extranjeros. Puede indicar un nacimiento posterior a 1945.",
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"]]},
vilma:{t:1,n:"Vilma De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermana de Liliana. Sólo por testimonio familiar. «Vilma» se populariza en Italia en los años 30 y 40.",
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"]]},
franca:{t:1,n:"Franca De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermana de Liliana. Sólo por testimonio familiar. «Franca» es de los nombres más frecuentes en la Italia de los años 30 y 40.\n\nTuvo una hija, ANNA, y por ella la rama sigue dos generaciones más: las nietas de Franca son Chiara y Giulia Polidori.",
  f:[["Hija","Anna","Testimonio de Federico Carlini, 27 de agosto de 2026."]],
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"],
     ["Testimonio de Federico Carlini, 27-ago-2026","La hija y las dos nietas."]]},
annaDF:{t:1,hyp:1,n:"Anna Gatti",d:"?",b:"friuli",pa:["franca"],
  note:"Hija de Franca De Faccio. El apellido no lo aportó el testimonio: se dedujo, y por eso entra como hipótesis.\n\nEl razonamiento: sus hijas se apellidan POLIDORI, o sea que Anna se casó con un Polidori y Polidori no es su apellido de soltera. Pero el testimonio dice que el tío de las chicas es STEFANO GATTI. Un tío puede serlo por dos caminos, y el más simple es que sea hermano de la madre — lo que haría a Anna una GATTI de soltera, hija de Franca De Faccio y de un señor Gatti.\n\nEs una deducción de una sola pieza y puede caerse: Stefano podría ser tío por el lado Polidori, o marido de una hermana. Alcanza con preguntar de quién es hermano Stefano para confirmarlo o tirarlo abajo.",
  f:[["Apellido","Gatti — deducido, no aportado","Si Stefano Gatti es hermano de Anna, Anna es Gatti de soltera y Franca se casó con un Gatti. Hay que confirmarlo preguntando de quién es hermano Stefano."],
     ["Hijas","Chiara y Giulia Polidori"]],
  c:[["Testimonio de Federico Carlini, 27-ago-2026"]]},
stefanoGatti:{t:1,hyp:1,n:"Stefano Gatti",d:"?",b:"friuli",pa:["franca"],
  note:"El testimonio lo da como TÍO de Chiara y Giulia Polidori. Dónde colgarlo del árbol es, por ahora, una deducción.\n\nEstá puesto como hermano de Anna —o sea, otro hijo de Franca— porque es la lectura que explica el apellido de las dos: si Anna era Gatti de soltera, Stefano es su hermano y todo cierra con una sola suposición.\n\nPero puede estar mal. Podría ser tío por el lado del padre de las chicas, o estar casado con una hermana del padre. Es una de las preguntas más baratas de resolver que quedan en el árbol.",
  f:[["Vínculo","Tío de Chiara y Giulia Polidori","Es lo único que dice el testimonio. Que sea hermano de Anna es deducción."]],
  c:[["Testimonio de Federico Carlini, 27-ago-2026"]]},
chiaraPol:{t:1,n:"Chiara Polidori",d:"?",b:"friuli",pa:["annaDF"],
  note:"Hija de Anna, nieta de Franca De Faccio. Sólo por testimonio familiar.",
  c:[["Testimonio de Federico Carlini, 27-ago-2026"]]},
giuliaPol:{t:1,n:"Giulia Polidori",d:"?",b:"friuli",pa:["annaDF"],
  note:"Hija de Anna, nieta de Franca De Faccio. Sólo por testimonio familiar.",
  c:[["Testimonio de Federico Carlini, 27-ago-2026"]]},
giorgio:{t:1,n:"Giorgio De Faccio",d:"~1925-45",b:"friuli",pa:["gbD","santaC"],
  note:"Hermano de Liliana, y el único del grupo con nombre tradicional friulano.\n\nTuvo al menos tres hijos: PIERGIORGIO, DANIELLA y GIOVANNI De Faccio. Son los primos hermanos de Patricia, y la rama viva más cercana por el lado friulano fuera de la línea directa. Si alguno conserva papeles de familia —o simplemente memoria— es de los contactos más valiosos que quedan por abrir.",
  f:[["Hijos","Piergiorgio · Daniella · Giovanni De Faccio","Testimonio de Federico Carlini, 26 de agosto de 2026."]],
  c:[["Testimonio familiar de Federico Carlini, 23-ago-2026"],
     ["Testimonio de Federico Carlini, 26-ago-2026","Los nombres de los tres hijos."]]},
piergiorgioDF:{t:1,n:"Piergiorgio De Faccio",d:"?",b:"friuli",pa:["giorgio"],
  note:"Hijo de Giorgio De Faccio, primo hermano de Patricia. Sólo por testimonio familiar: no hay acta todavía. Su nombre repite el del padre, que es costumbre corriente en el Friuli.",
  c:[["Testimonio de Federico Carlini, 26-ago-2026"]]},
daniellaDF:{t:1,n:"Daniella De Faccio",d:"?",b:"friuli",pa:["giorgio"],
  note:"Hija de Giorgio De Faccio, prima hermana de Patricia. Sólo por testimonio familiar.",
  c:[["Testimonio de Federico Carlini, 26-ago-2026"]]},
giovanniDF:{t:1,n:"Giovanni De Faccio",d:"?",b:"friuli",pa:["giorgio"],
  note:"Hijo de Giorgio De Faccio, primo hermano de Patricia. Sólo por testimonio familiar.\n\nLleva el nombre del abuelo, Giovanni Battista De Faccio — la regla onomástica friulana funcionando igual que la siciliana del otro lado del árbol.",
  c:[["Testimonio de Federico Carlini, 26-ago-2026"]]},

/* ---- MORELLO: la candidata de Codroipo ---- */
ferdinandoM:{n:"Ferdinando Morello",d:"?",b:"friuli",
  note:"Padre de la única Ida Morello indexada en toda la provincia de Udine. El vínculo con nuestra Ida está SIN CONFIRMAR.",
  c:[["FamilySearch, Udine 1871-1911, nacimiento de Codroipo 1895"]]},
mariaZ:{n:"Maria Zanin",d:"?",b:"friuli",
  c:[["FamilySearch, Udine 1871-1911, nacimiento de Codroipo 1895"]]},

/* ---- CAGNOLINI de Latisana: tres generaciones documentadas ---- */
giuseppeEM:{nac:["it"],zn:"Latisana",n:"Giuseppe Enrico Marzio Cagnolini",d:"1880",b:"friuli",pa:["luigiCag","santaPin"],
  note:"Candidato a padre de Santa. Tendría 20 años en 1900, la edad justa. SIN CONFIRMAR: hace falta el acta de nacimiento de Santa.",
  f:[["Nacimiento","29 de agosto de 1880, Latisana"]],
  c:[["Latisana 1880, Nati","Giuseppe Enrico Marzio Cagnolini, di Luigi e Santa Pinzan"]]},
luigiCag:{docs:[["Acta de defunción","Comune di Latisana, posterior a 1911 — CONFIRMARÍA EL ENLACE","pedir"],["Acta de matrimonio","Parroquia de Latisana, anterior a sept-1871","pedir"]],n:"Luigi Cagnolini",d:"~1840",b:"friuli",pa:["carloCag","caterinaFab"],hyp:1,
  note:"EL ESLABÓN QUE UNE LAS DOS MITADES, y es hipótesis, no dato. Ningún acta dice quiénes fueron sus padres: se casó con Santa Pinzani antes de septiembre de 1871 —o sea dentro del muro austríaco, cuando en Friuli registraban los párrocos y no el Estado— y murió después de 1911, ya fuera del alcance de Antenati y de FamilySearch. Por eso nunca aparece como protagonista de un acta: en los registros de Latisana figura siempre como padre de alguien.\n\nLo que sí lo ata a Carlo y Caterina son tres cosas que apuntan al mismo lugar. Primera, la costumbre onomástica italiana: la primera hija lleva el nombre de la abuela paterna, y la primera hija de Luigi se llamó CATERINA Anna Vittoria, nacida en 1867 — el nombre exacto de Caterina Fabbroni. Segunda, las fechas: Carlo tenía treinta y dos años en 1840, la edad justa, y su otro hijo conocido, Giuseppe, es de 1830. Tercera, en la Latisana de esos años no hay otra familia Cagnolini: todos los que aparecen en el estado civil descienden de Andrea Spiridion.",
  f:[["Hipótesis","Hijo de Carlo Cagnolini y Caterina Fabbroni","Apoyada en la regla onomástica (su primera hija se llamó Caterina), en la edad de Carlo en 1840 y en que no hay otra familia Cagnolini en Latisana."],
     ["Casado con","Santa Pinzani, antes de septiembre de 1871","El matrimonio cae dentro del período austríaco: lo registró la parroquia, no el Estado. Por eso no está en ningún archivo digitalizado."],
     ["Muerto después de","1911","No figura como difunto en el estado civil de Udine 1871-1911."],
     ["Hijos documentados","Caterina Anna Vittoria (1867) · Marzio (1872) · Giuseppe (1874) · Erminia Virginia Battistina Antonia (1875) · Giuseppe Enrico Marzio (1880)"],
     ["Lo que lo confirmaría","Su acta de defunción, en el Comune di Latisana","Las actas de defunción italianas nombran a los padres del difunto. Como murió después de 1911, hay que pedirla al comune: no está online."]],
  c:[["Latisana, Nati e Matrimoni 1867-1880"],
     ["FamilySearch, Italia, Udine, Stato Civile (Archivio di Stato), 1806-1815, 1871-1911"]]},
caterinaAnnaVittoria:{nac:["it"],zn:"Latisana",n:"Caterina Anna Vittoria Cagnolini",d:"1867",b:"friuli",pa:["luigiCag","santaPin"],
  note:"La primera hija de Luigi, y la pieza que sostiene toda la reconstrucción. Por la costumbre italiana, la primera hija lleva el nombre de la abuela paterna — y Caterina es el nombre de la mujer de Carlo Cagnolini. Se casó en Latisana; el acta la registra nacida en 1867.",
  f:[["Nacimiento","1867, Latisana"],
     ["Matrimonio","Registrado en el estado civil de Udine"]],
  c:[["FamilySearch, Udine, Stato Civile 1871-1911, matrimonio"]]},
pierinaGne:{n:"Pierina Gnesutta",d:"?",b:"friuli",
  note:"Mujer de Angelo Cagnolini, el hijo menor de Andrea Spiridion. Aparecida el 24-ago-2026 en el acta de matrimonio de su hija.",
  c:[["Latisana 1884, Matrimoni, acta n. 7","Carolina Maria Cagnolini, figlia di Angelo Cagnolini e Pierina Gnesutta"]]},
carolinaMaria:{nac:["it"],zn:"Latisana",n:"Carolina Maria Cagnolini",d:"1857",b:"friuli",pa:["angeloCag","pierinaGne"],
  note:"Nacida en Latisana en 1857, casada el 23 de febrero de 1884 con Francesco Guido Stoppini, de Acqui. Su acta es la que dio el nombre de su madre.",
  f:[["Nacimiento","1857, Latisana"],
     ["Matrimonio","23 de febrero de 1884, acta n. 7"],
     ["Marido","Francesco Guido Stoppini, n. ~1852 en Acqui"]],
  c:[["Latisana 1884, Matrimoni, acta n. 7"]]},
santaPin:{n:"Santa Pinzani",d:"~1845",b:"friuli",
  note:"La clave onomástica de toda esta rama. Por la costumbre italiana, una nieta suya nacida hacia 1900 se habría llamado Santa Cagnolini — que es exactamente el nombre que buscamos.",
  f:[["Variante","Pinzan, en el acta de 1880"]],
  c:[["Latisana, Nati 1867-1880"]]},
andreaCag:{nac:["gr"],zn:"Corfú",docs:[["Acta de matrimonio","Latisana 1806, Matrimoni, atto n. 13 (16-ene-1807)","online"],["Partida de nacimiento","Corfú, 26-dic-1778 — citada en el acta de 1807, sin localizar","pedir"]],pr:"Speziale (boticario) · después possidente",n:"Andrea Spiridion Cagnolin",d:"1778 – ?",b:"friuli",pa:["giuseppeCagPadre","vicenzaCasanova"],
  note:"El acta de su matrimonio, Latisana, 16 de enero de 1807, dio vuelta toda la rama. No nació en Friuli: nació el 26 de diciembre de 1778 EN LA CIUDAD DE CORFÚ, que entonces era territorio de la República de Venecia. Su segundo nombre lo confirma solo: Spiridion es San Spiridione, el patrono de Corfú, un nombre que en el Friuli de 1778 no se le ponía a nadie. Cuando se casó tenía veintiocho años y era SPEZIALE —boticario—; seis años después, en el acta de su hija, ya figura como possidente. Firmó los dos documentos de puño y letra, en un registro donde casi todos los demás terminan con la fórmula «per non saper esso scrivere».",
  f:[["Nacimiento","26 de diciembre de 1778, ciudad de Corfú","El acta de matrimonio cita su partida de nacimiento, fechada el 30 de agosto de 1779 «S.V.» — stile veneto, el calendario de la República."],
     ["Oficio en 1807","Speziale (boticario)"],
     ["Condición en 1813","Possidente"],
     ["Domicilio","Borgo dell'Annunziata, Latisana"],
     ["Matrimonio","16 de enero de 1807, Latisana, acto n. 13"],
     ["Sabía escribir","Firmó su propia acta de matrimonio y la de su hija"]],
  img:[["registros/latisana-matrimonios-1807-acta13-cagnolin.jpg","Latisana, Matrimoni 1806, acto n. 13 (16 de enero de 1807). Nombra a los cuatro padres y dice que Andrea nació en Corfú."],["registros/latisana-nacimientos-1813-acta65-cagnolini.jpg","Latisana, Nati 1813, acta n. 65. Nombra a Andrea, a su padre Giuseppe, y a Marianna con su padre Angelo."],["registros/latisana-indice-1813-cagnolini.jpg","La tavola alfabetica de 1813, donde apareció la pista: «Cagnolini Elisabetta Catterina · Latisana · 11 giugno · atto 65»."]],
  url:"https://antenati.cultura.gov.it/ark:/12657/an_ua657282",
  c:[["Latisana 1806, Matrimoni, atto n. 13","il Sig.r Andrea Spiridion Cagnolin della età di anni ventiotto compiti, di Professione Speziale, domiciliato in questa Comune figlio del q.m Sig.r Giuseppe Cagnolin, e della Sig.ra Vicenza Casanova"],
     ["Latisana 1806, Matrimoni, atto n. 13","assicura egli esser nato li ventisei Decembre mille settecento settantotto nella Città di Corfù"],
     ["Latisana 1813, Nati, atto n. 65","il Signor Andrea del fu Giuseppe Cagnolini, d'anni trentaquattro, possidente, domiciliato in questo Capoluogo nel Borgo dell'Annunziata"],
     ["Latisana, Morti 1879-1888"]]},
giuseppeCagPadre:{pr:"Possidente, en Corfú",n:"Giuseppe Cagnolin",d:"~1745",b:"friuli",open:true,
  note:"La persona más antigua del árbol, y ahora también la más lejana geográficamente. Su hijo nació en Corfú en 1778, así que en esa fecha él vivía en las Islas Jónicas venecianas. Ya había muerto en enero de 1807, cuando el acta de matrimonio de Andrea lo llama «q.m» —quondam, el difunto— y hace que sea la madre quien firme el consentimiento. Su matrimonio con Vicenza Casanova caería entre 1770 y 1778, y los registros de esos años no están en Antenati: están en los archivos venecianos y en los de Corfú.",
  f:[["Muerto antes de","enero de 1807"],
     ["Residía en","Corfú, República de Venecia, al menos en 1778"]],
  c:[["Latisana 1806, Matrimoni, atto n. 13","figlio del q.m Sig.r Giuseppe Cagnolin"],
     ["Latisana 1813, Nati, atto n. 65","Andrea del fu Giuseppe Cagnolini"]]},
vicenzaCasanova:{n:"Vicenza Casanova",d:"~1750",b:"friuli",open:true,
  note:"La madre de Andrea, y la única de los cuatro abuelos de esta generación que seguía viva. El 14 de enero de 1807 firmó desde algún lado el consentimiento escrito para que su hijo se casara —el acta lo consigna expresamente «essendo morto il di lui Padre»—. Casanova es apellido veneciano, no friulano ni griego: encaja con una familia de súbditos de la Serenísima instalada en Corfú.",
  f:[["Viva en","enero de 1807"],
     ["Consentimiento","14 de enero de 1807, por escrito"]],
  c:[["Latisana 1806, Matrimoni, atto n. 13","il consenso in iscritto in data quattordici Gennaro corrente della Sig.ra Vicenza Casanova madre dello Sposo essendo morto il di lui Padre"]]},
angeloDonate:{n:"Angelo Donati",d:"~1750",b:"friuli",open:true,
  note:"Padre de Marianna. Muerto ya en enero de 1807: el acta omite los actos respetuosos de la novia «per essere morti li suoi ascendenti», o sea que para esa fecha no le quedaba ningún ascendiente vivo. Su matrimonio con Paolina Bonfin sería anterior a 1781 y cae dentro de los registros parroquiales de Latisana, todavía sin indexar. El apellido aparece como Donati en 1807 y como Donate en 1813 — la misma inestabilidad ortográfica de siempre.",
  c:[["Latisana 1806, Matrimoni, atto n. 13","figlia del q.m Sig.r Angelo Donati, e della q.m Sig.ra Paolina Bonfin"],
     ["Latisana 1813, Nati, atto n. 65","della Signora Marianna del fu Angelo Donate"]]},
paolinaBonfin:{n:"Paolina Bonfin",d:"~1755",b:"friuli",open:true,
  note:"La madre de Marianna, aparecida recién ahora. También «q.m» en enero de 1807: los dos padres de la novia estaban muertos antes de que ella cumpliera veintiséis años. El apellido está escrito Bonfin en el acta; podría ser también Bonfio, y podría emparentar con los Bonfin de la Bassa Friulana.",
  f:[["Muerta antes de","enero de 1807"],
     ["Lectura del apellido","Bonfin en el acta; posible Bonfio"]],
  c:[["Latisana 1806, Matrimoni, atto n. 13","e della q.m Sig.ra Paolina Bonfin"]]},
mariannaDon:{nac:["it"],zn:"Latisana",docs:[["Acta de matrimonio","Latisana 1806, Matrimoni, atto n. 13","online"],["Acta de nacimiento","Latisana, 3-ago-1781 — registro parroquial","pedir"]],pr:"Possidente",n:"Maria Anna (Marianna) Donati",d:"1781 – ?",b:"friuli",pa:["angeloDonate","paolinaBonfin"],
  note:"Nació en Latisana el 3 de agosto de 1781. Se casó a los veinticinco años con un boticario recién llegado de Corfú. Ya era possidente por derecho propio antes de casarse —el acta se lo consigna a ella sola, algo que en esa época casi no se escribía de una mujer— pero no sabía escribir: firmó por ella Gio Carlo Fabani, el maestro de música del pueblo, «per non saper essa scrivere».",
  f:[["Nacimiento","3 de agosto de 1781, Latisana"],
     ["Condición","Possidente, ya soltera"],
     ["Matrimonio","16 de enero de 1807, Latisana, acto n. 13"],
     ["No sabía escribir","Firmó por ella un testigo"],
     ["Variantes","Maria Anna en 1807, Marianna en la firma, Marianna del fu Angelo Donate en 1813"]],
  img:[["registros/latisana-matrimonios-1807-acta13-cagnolin.jpg","Latisana, Matrimoni 1806, acto n. 13. «figlia del q.m Sig.r Angelo Donati, e della q.m Sig.ra Paolina Bonfin»."]],
  url:"https://antenati.cultura.gov.it/ark:/12657/an_ua657282",
  c:[["Latisana 1806, Matrimoni, atto n. 13","la Sig.ra Maria Anna Donati della età di anni venticinque compiti, Possidente, domiciliata in questa Comune"],
     ["Latisana 1806, Matrimoni, atto n. 13","assicura esser Ella nata il giorno tre Agosto dell'anno mille settecento ottanta uno in questa Comune"],
     ["Latisana 1813, Nati, atto n. 65","della Signora Marianna del fu Angelo Donate, d'anni trentuno, possidente"]]},
carloCag:{pr:"Possidente",n:"Carlo Cagnolini",d:"1808 – 1879",b:"friuli",pa:["andreaCag","mariannaDon"],
  c:[["Latisana, Morti, defunción 3-may-1879"]]},
elisabettaCag:{nac:["it"],zn:"Latisana",docs:[["Acta de nacimiento","Latisana 1813, Nati, atto n. 65","online"]],n:"Elisabetta Catterina Cagnolini",d:"1813 – 1881",b:"friuli",pa:["andreaCag","mariannaDon"],
  note:"Casada con Gio Batta Toppani. Una hija suya se llamó Santa Toppani: el nombre circula por las dos ramas de la familia mucho antes de llegar a Santa Cagnolini.",
  f:[["Nacimiento","10 de junio de 1813, a las cinco de la mañana, en el domicilio familiar del Borgo dell'Annunziata"],
     ["Nombres completos","Elisabetta e Catterina, según el acta"],
     ["Defunción","16 de junio de 1881"]],
  url:"https://antenati.cultura.gov.it/ark:/12657/an_ua657391",
  c:[["Latisana 1813, Nati, atto n. 65","un infante di sesso femminino, nata nel di lui domicilio il giorno di jeri alle ore cinque antemeridiane, cui furon posti li nomi di Elisabetta e Catterina"],
     ["Latisana, Morti, defunción 16-jun-1881"]]},
angeloCag:{n:"Angelo Cagnolini",d:"1822 – 1888",b:"friuli",pa:["andreaCag","mariannaDon"],
  c:[["Latisana, Morti, defunción 23-ene-1888"]]},
giuseppeCag:{n:"Giuseppe Cagnolini",d:"1830 – 1898",b:"friuli",pa:["carloCag","caterinaFab"],
  c:[["Latisana, Morti, defunción 9-mar-1898"]]},
caterinaFab:{n:"Caterina Fabbroni",d:"?",b:"friuli",c:[["Latisana, Morti 1879"]]},
carloCag2:{n:"Carlo Cagnolini",d:"1859 – 1892",b:"friuli",pa:["giuseppeCag","teresaMoz"],
  c:[["Latisana, Morti, defunción 19-mar-1892"]]},
teresaMoz:{n:"Teresa Mozzoni",d:"?",b:"friuli",c:[["Latisana, Morti 1898"]]},
};
